// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-migration-service/application"
	"github.com/ONSdigital/dis-migration-service/domain"
	"sync"
)

// Ensure, that JobServiceMock does implement application.JobService.
// If this is not the case, regenerate this file with moq.
var _ application.JobService = &JobServiceMock{}

// JobServiceMock is a mock implementation of application.JobService.
//
// 	func TestSomethingThatUsesJobService(t *testing.T) {
//
// 		// make and configure a mocked application.JobService
// 		mockedJobService := &JobServiceMock{
// 			CountTasksByJobIDFunc: func(ctx context.Context, jobID string) (int, error) {
// 				panic("mock out the CountTasksByJobID method")
// 			},
// 			CreateJobFunc: func(ctx context.Context, jobConfig *domain.JobConfig) (*domain.Job, error) {
// 				panic("mock out the CreateJob method")
// 			},
// 			CreateJobNumberCounterFunc: func(ctx context.Context) error {
// 				panic("mock out the CreateJobNumberCounter method")
// 			},
// 			GetJobFunc: func(ctx context.Context, jobID string) (*domain.Job, error) {
// 				panic("mock out the GetJob method")
// 			},
// 			GetJobTasksFunc: func(ctx context.Context, jobID string, limit int, offset int) ([]*domain.Task, int, error) {
// 				panic("mock out the GetJobTasks method")
// 			},
// 			GetJobsFunc: func(ctx context.Context, limit int, offset int) ([]*domain.Job, int, error) {
// 				panic("mock out the GetJobs method")
// 			},
// 		}
//
// 		// use mockedJobService in code that requires application.JobService
// 		// and then make assertions.
//
// 	}
type JobServiceMock struct {
	// CountTasksByJobIDFunc mocks the CountTasksByJobID method.
	CountTasksByJobIDFunc func(ctx context.Context, jobID string) (int, error)

	// CreateJobFunc mocks the CreateJob method.
	CreateJobFunc func(ctx context.Context, jobConfig *domain.JobConfig) (*domain.Job, error)

	// CreateJobNumberCounterFunc mocks the CreateJobNumberCounter method.
	CreateJobNumberCounterFunc func(ctx context.Context) error

	// GetJobFunc mocks the GetJob method.
	GetJobFunc func(ctx context.Context, jobID string) (*domain.Job, error)

	// GetJobTasksFunc mocks the GetJobTasks method.
	GetJobTasksFunc func(ctx context.Context, jobID string, limit int, offset int) ([]*domain.Task, int, error)

	// GetJobsFunc mocks the GetJobs method.
	GetJobsFunc func(ctx context.Context, limit int, offset int) ([]*domain.Job, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// CountTasksByJobID holds details about calls to the CountTasksByJobID method.
		CountTasksByJobID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
		}
		// CreateJob holds details about calls to the CreateJob method.
		CreateJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobConfig is the jobConfig argument value.
			JobConfig *domain.JobConfig
		}
		// CreateJobNumberCounter holds details about calls to the CreateJobNumberCounter method.
		CreateJobNumberCounter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetJob holds details about calls to the GetJob method.
		GetJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
		}
		// GetJobTasks holds details about calls to the GetJobTasks method.
		GetJobTasks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetJobs holds details about calls to the GetJobs method.
		GetJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
	}
	lockCountTasksByJobID      sync.RWMutex
	lockCreateJob              sync.RWMutex
	lockCreateJobNumberCounter sync.RWMutex
	lockGetJob                 sync.RWMutex
	lockGetJobTasks            sync.RWMutex
	lockGetJobs                sync.RWMutex
}

// CountTasksByJobID calls CountTasksByJobIDFunc.
func (mock *JobServiceMock) CountTasksByJobID(ctx context.Context, jobID string) (int, error) {
	if mock.CountTasksByJobIDFunc == nil {
		panic("JobServiceMock.CountTasksByJobIDFunc: method is nil but JobService.CountTasksByJobID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		JobID string
	}{
		Ctx:   ctx,
		JobID: jobID,
	}
	mock.lockCountTasksByJobID.Lock()
	mock.calls.CountTasksByJobID = append(mock.calls.CountTasksByJobID, callInfo)
	mock.lockCountTasksByJobID.Unlock()
	return mock.CountTasksByJobIDFunc(ctx, jobID)
}

// CountTasksByJobIDCalls gets all the calls that were made to CountTasksByJobID.
// Check the length with:
//     len(mockedJobService.CountTasksByJobIDCalls())
func (mock *JobServiceMock) CountTasksByJobIDCalls() []struct {
	Ctx   context.Context
	JobID string
} {
	var calls []struct {
		Ctx   context.Context
		JobID string
	}
	mock.lockCountTasksByJobID.RLock()
	calls = mock.calls.CountTasksByJobID
	mock.lockCountTasksByJobID.RUnlock()
	return calls
}

// CreateJob calls CreateJobFunc.
func (mock *JobServiceMock) CreateJob(ctx context.Context, jobConfig *domain.JobConfig) (*domain.Job, error) {
	if mock.CreateJobFunc == nil {
		panic("JobServiceMock.CreateJobFunc: method is nil but JobService.CreateJob was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		JobConfig *domain.JobConfig
	}{
		Ctx:       ctx,
		JobConfig: jobConfig,
	}
	mock.lockCreateJob.Lock()
	mock.calls.CreateJob = append(mock.calls.CreateJob, callInfo)
	mock.lockCreateJob.Unlock()
	return mock.CreateJobFunc(ctx, jobConfig)
}

// CreateJobCalls gets all the calls that were made to CreateJob.
// Check the length with:
//     len(mockedJobService.CreateJobCalls())
func (mock *JobServiceMock) CreateJobCalls() []struct {
	Ctx       context.Context
	JobConfig *domain.JobConfig
} {
	var calls []struct {
		Ctx       context.Context
		JobConfig *domain.JobConfig
	}
	mock.lockCreateJob.RLock()
	calls = mock.calls.CreateJob
	mock.lockCreateJob.RUnlock()
	return calls
}

// CreateJobNumberCounter calls CreateJobNumberCounterFunc.
func (mock *JobServiceMock) CreateJobNumberCounter(ctx context.Context) error {
	if mock.CreateJobNumberCounterFunc == nil {
		panic("JobServiceMock.CreateJobNumberCounterFunc: method is nil but JobService.CreateJobNumberCounter was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCreateJobNumberCounter.Lock()
	mock.calls.CreateJobNumberCounter = append(mock.calls.CreateJobNumberCounter, callInfo)
	mock.lockCreateJobNumberCounter.Unlock()
	return mock.CreateJobNumberCounterFunc(ctx)
}

// CreateJobNumberCounterCalls gets all the calls that were made to CreateJobNumberCounter.
// Check the length with:
//     len(mockedJobService.CreateJobNumberCounterCalls())
func (mock *JobServiceMock) CreateJobNumberCounterCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCreateJobNumberCounter.RLock()
	calls = mock.calls.CreateJobNumberCounter
	mock.lockCreateJobNumberCounter.RUnlock()
	return calls
}

// GetJob calls GetJobFunc.
func (mock *JobServiceMock) GetJob(ctx context.Context, jobID string) (*domain.Job, error) {
	if mock.GetJobFunc == nil {
		panic("JobServiceMock.GetJobFunc: method is nil but JobService.GetJob was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		JobID string
	}{
		Ctx:   ctx,
		JobID: jobID,
	}
	mock.lockGetJob.Lock()
	mock.calls.GetJob = append(mock.calls.GetJob, callInfo)
	mock.lockGetJob.Unlock()
	return mock.GetJobFunc(ctx, jobID)
}

// GetJobCalls gets all the calls that were made to GetJob.
// Check the length with:
//     len(mockedJobService.GetJobCalls())
func (mock *JobServiceMock) GetJobCalls() []struct {
	Ctx   context.Context
	JobID string
} {
	var calls []struct {
		Ctx   context.Context
		JobID string
	}
	mock.lockGetJob.RLock()
	calls = mock.calls.GetJob
	mock.lockGetJob.RUnlock()
	return calls
}

// GetJobTasks calls GetJobTasksFunc.
func (mock *JobServiceMock) GetJobTasks(ctx context.Context, jobID string, limit int, offset int) ([]*domain.Task, int, error) {
	if mock.GetJobTasksFunc == nil {
		panic("JobServiceMock.GetJobTasksFunc: method is nil but JobService.GetJobTasks was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		JobID  string
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		JobID:  jobID,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockGetJobTasks.Lock()
	mock.calls.GetJobTasks = append(mock.calls.GetJobTasks, callInfo)
	mock.lockGetJobTasks.Unlock()
	return mock.GetJobTasksFunc(ctx, jobID, limit, offset)
}

// GetJobTasksCalls gets all the calls that were made to GetJobTasks.
// Check the length with:
//     len(mockedJobService.GetJobTasksCalls())
func (mock *JobServiceMock) GetJobTasksCalls() []struct {
	Ctx    context.Context
	JobID  string
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		JobID  string
		Limit  int
		Offset int
	}
	mock.lockGetJobTasks.RLock()
	calls = mock.calls.GetJobTasks
	mock.lockGetJobTasks.RUnlock()
	return calls
}

// GetJobs calls GetJobsFunc.
func (mock *JobServiceMock) GetJobs(ctx context.Context, limit int, offset int) ([]*domain.Job, int, error) {
	if mock.GetJobsFunc == nil {
		panic("JobServiceMock.GetJobsFunc: method is nil but JobService.GetJobs was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockGetJobs.Lock()
	mock.calls.GetJobs = append(mock.calls.GetJobs, callInfo)
	mock.lockGetJobs.Unlock()
	return mock.GetJobsFunc(ctx, limit, offset)
}

// GetJobsCalls gets all the calls that were made to GetJobs.
// Check the length with:
//     len(mockedJobService.GetJobsCalls())
func (mock *JobServiceMock) GetJobsCalls() []struct {
	Ctx    context.Context
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Limit  int
		Offset int
	}
	mock.lockGetJobs.RLock()
	calls = mock.calls.GetJobs
	mock.lockGetJobs.RUnlock()
	return calls
}
