// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-migration-service/application"
	"github.com/ONSdigital/dis-migration-service/domain"
	"sync"
)

// Ensure, that JobServiceMock does implement application.JobService.
// If this is not the case, regenerate this file with moq.
var _ application.JobService = &JobServiceMock{}

// JobServiceMock is a mock implementation of application.JobService.
//
// 	func TestSomethingThatUsesJobService(t *testing.T) {
//
// 		// make and configure a mocked application.JobService
// 		mockedJobService := &JobServiceMock{
// 			ClaimJobFunc: func(ctx context.Context) (*domain.Job, error) {
// 				panic("mock out the ClaimJob method")
// 			},
// 			ClaimTaskFunc: func(ctx context.Context) (*domain.Task, error) {
// 				panic("mock out the ClaimTask method")
// 			},
// 			CountEventsByJobNumberFunc: func(ctx context.Context, jobNumber int) (int, error) {
// 				panic("mock out the CountEventsByJobNumber method")
// 			},
// 			CountTasksByJobNumberFunc: func(ctx context.Context, jobNumber int) (int, error) {
// 				panic("mock out the CountTasksByJobNumber method")
// 			},
// 			CreateEventFunc: func(ctx context.Context, jobNumber int, event *domain.Event) (*domain.Event, error) {
// 				panic("mock out the CreateEvent method")
// 			},
// 			CreateJobFunc: func(ctx context.Context, jobConfig *domain.JobConfig) (*domain.Job, error) {
// 				panic("mock out the CreateJob method")
// 			},
// 			CreateTaskFunc: func(ctx context.Context, jobNumber int, task *domain.Task) (*domain.Task, error) {
// 				panic("mock out the CreateTask method")
// 			},
// 			GetJobFunc: func(ctx context.Context, jobNumber int) (*domain.Job, error) {
// 				panic("mock out the GetJob method")
// 			},
// 			GetJobEventsFunc: func(ctx context.Context, jobNumber int, limit int, offset int) ([]*domain.Event, int, error) {
// 				panic("mock out the GetJobEvents method")
// 			},
// 			GetJobNumberCounterFunc: func(ctx context.Context) (*domain.Counter, error) {
// 				panic("mock out the GetJobNumberCounter method")
// 			},
// 			GetJobTasksFunc: func(ctx context.Context, states []domain.TaskState, jobNumber int, limit int, offset int) ([]*domain.Task, int, error) {
// 				panic("mock out the GetJobTasks method")
// 			},
// 			GetJobsFunc: func(ctx context.Context, states []domain.JobState, limit int, offset int) ([]*domain.Job, int, error) {
// 				panic("mock out the GetJobs method")
// 			},
// 			GetNextJobNumberCounterFunc: func(ctx context.Context) (*domain.Counter, error) {
// 				panic("mock out the GetNextJobNumberCounter method")
// 			},
// 			UpdateJobStateFunc: func(ctx context.Context, jobNumber int, newState domain.JobState) error {
// 				panic("mock out the UpdateJobState method")
// 			},
// 			UpdateTaskFunc: func(ctx context.Context, task *domain.Task) error {
// 				panic("mock out the UpdateTask method")
// 			},
// 			UpdateTaskStateFunc: func(ctx context.Context, taskID string, newState domain.TaskState) error {
// 				panic("mock out the UpdateTaskState method")
// 			},
// 		}
//
// 		// use mockedJobService in code that requires application.JobService
// 		// and then make assertions.
//
// 	}
type JobServiceMock struct {
	// ClaimJobFunc mocks the ClaimJob method.
	ClaimJobFunc func(ctx context.Context) (*domain.Job, error)

	// ClaimTaskFunc mocks the ClaimTask method.
	ClaimTaskFunc func(ctx context.Context) (*domain.Task, error)

	// CountEventsByJobNumberFunc mocks the CountEventsByJobNumber method.
	CountEventsByJobNumberFunc func(ctx context.Context, jobNumber int) (int, error)

	// CountTasksByJobNumberFunc mocks the CountTasksByJobNumber method.
	CountTasksByJobNumberFunc func(ctx context.Context, jobNumber int) (int, error)

	// CreateEventFunc mocks the CreateEvent method.
	CreateEventFunc func(ctx context.Context, jobNumber int, event *domain.Event) (*domain.Event, error)

	// CreateJobFunc mocks the CreateJob method.
	CreateJobFunc func(ctx context.Context, jobConfig *domain.JobConfig) (*domain.Job, error)

	// CreateTaskFunc mocks the CreateTask method.
	CreateTaskFunc func(ctx context.Context, jobNumber int, task *domain.Task) (*domain.Task, error)

	// GetJobFunc mocks the GetJob method.
	GetJobFunc func(ctx context.Context, jobNumber int) (*domain.Job, error)

	// GetJobEventsFunc mocks the GetJobEvents method.
	GetJobEventsFunc func(ctx context.Context, jobNumber int, limit int, offset int) ([]*domain.Event, int, error)

	// GetJobNumberCounterFunc mocks the GetJobNumberCounter method.
	GetJobNumberCounterFunc func(ctx context.Context) (*domain.Counter, error)

	// GetJobTasksFunc mocks the GetJobTasks method.
	GetJobTasksFunc func(ctx context.Context, states []domain.TaskState, jobNumber int, limit int, offset int) ([]*domain.Task, int, error)

	// GetJobsFunc mocks the GetJobs method.
	GetJobsFunc func(ctx context.Context, states []domain.JobState, limit int, offset int) ([]*domain.Job, int, error)

	// GetNextJobNumberCounterFunc mocks the GetNextJobNumberCounter method.
	GetNextJobNumberCounterFunc func(ctx context.Context) (*domain.Counter, error)

	// UpdateJobStateFunc mocks the UpdateJobState method.
	UpdateJobStateFunc func(ctx context.Context, jobNumber int, newState domain.JobState) error

	// UpdateTaskFunc mocks the UpdateTask method.
	UpdateTaskFunc func(ctx context.Context, task *domain.Task) error

	// UpdateTaskStateFunc mocks the UpdateTaskState method.
	UpdateTaskStateFunc func(ctx context.Context, taskID string, newState domain.TaskState) error

	// calls tracks calls to the methods.
	calls struct {
		// ClaimJob holds details about calls to the ClaimJob method.
		ClaimJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ClaimTask holds details about calls to the ClaimTask method.
		ClaimTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// CountEventsByJobNumber holds details about calls to the CountEventsByJobNumber method.
		CountEventsByJobNumber []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobNumber is the jobNumber argument value.
			JobNumber int
		}
		// CountTasksByJobNumber holds details about calls to the CountTasksByJobNumber method.
		CountTasksByJobNumber []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobNumber is the jobNumber argument value.
			JobNumber int
		}
		// CreateEvent holds details about calls to the CreateEvent method.
		CreateEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobNumber is the jobNumber argument value.
			JobNumber int
			// Event is the event argument value.
			Event *domain.Event
		}
		// CreateJob holds details about calls to the CreateJob method.
		CreateJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobConfig is the jobConfig argument value.
			JobConfig *domain.JobConfig
		}
		// CreateTask holds details about calls to the CreateTask method.
		CreateTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobNumber is the jobNumber argument value.
			JobNumber int
			// Task is the task argument value.
			Task *domain.Task
		}
		// GetJob holds details about calls to the GetJob method.
		GetJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobNumber is the jobNumber argument value.
			JobNumber int
		}
		// GetJobEvents holds details about calls to the GetJobEvents method.
		GetJobEvents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobNumber is the jobNumber argument value.
			JobNumber int
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetJobNumberCounter holds details about calls to the GetJobNumberCounter method.
		GetJobNumberCounter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// GetJobTasks holds details about calls to the GetJobTasks method.
		GetJobTasks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// States is the states argument value.
			States []domain.TaskState
			// JobNumber is the jobNumber argument value.
			JobNumber int
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetJobs holds details about calls to the GetJobs method.
		GetJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// States is the states argument value.
			States []domain.JobState
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetNextJobNumberCounter holds details about calls to the GetNextJobNumberCounter method.
		GetNextJobNumberCounter []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateJobState holds details about calls to the UpdateJobState method.
		UpdateJobState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobNumber is the jobNumber argument value.
			JobNumber int
			// NewState is the newState argument value.
			NewState domain.JobState
		}
		// UpdateTask holds details about calls to the UpdateTask method.
		UpdateTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Task is the task argument value.
			Task *domain.Task
		}
		// UpdateTaskState holds details about calls to the UpdateTaskState method.
		UpdateTaskState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TaskID is the taskID argument value.
			TaskID string
			// NewState is the newState argument value.
			NewState domain.TaskState
		}
	}
	lockClaimJob                sync.RWMutex
	lockClaimTask               sync.RWMutex
	lockCountEventsByJobNumber  sync.RWMutex
	lockCountTasksByJobNumber   sync.RWMutex
	lockCreateEvent             sync.RWMutex
	lockCreateJob               sync.RWMutex
	lockCreateTask              sync.RWMutex
	lockGetJob                  sync.RWMutex
	lockGetJobEvents            sync.RWMutex
	lockGetJobNumberCounter     sync.RWMutex
	lockGetJobTasks             sync.RWMutex
	lockGetJobs                 sync.RWMutex
	lockGetNextJobNumberCounter sync.RWMutex
	lockUpdateJobState          sync.RWMutex
	lockUpdateTask              sync.RWMutex
	lockUpdateTaskState         sync.RWMutex
}

// ClaimJob calls ClaimJobFunc.
func (mock *JobServiceMock) ClaimJob(ctx context.Context) (*domain.Job, error) {
	if mock.ClaimJobFunc == nil {
		panic("JobServiceMock.ClaimJobFunc: method is nil but JobService.ClaimJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClaimJob.Lock()
	mock.calls.ClaimJob = append(mock.calls.ClaimJob, callInfo)
	mock.lockClaimJob.Unlock()
	return mock.ClaimJobFunc(ctx)
}

// ClaimJobCalls gets all the calls that were made to ClaimJob.
// Check the length with:
//     len(mockedJobService.ClaimJobCalls())
func (mock *JobServiceMock) ClaimJobCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClaimJob.RLock()
	calls = mock.calls.ClaimJob
	mock.lockClaimJob.RUnlock()
	return calls
}

// ClaimTask calls ClaimTaskFunc.
func (mock *JobServiceMock) ClaimTask(ctx context.Context) (*domain.Task, error) {
	if mock.ClaimTaskFunc == nil {
		panic("JobServiceMock.ClaimTaskFunc: method is nil but JobService.ClaimTask was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClaimTask.Lock()
	mock.calls.ClaimTask = append(mock.calls.ClaimTask, callInfo)
	mock.lockClaimTask.Unlock()
	return mock.ClaimTaskFunc(ctx)
}

// ClaimTaskCalls gets all the calls that were made to ClaimTask.
// Check the length with:
//     len(mockedJobService.ClaimTaskCalls())
func (mock *JobServiceMock) ClaimTaskCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClaimTask.RLock()
	calls = mock.calls.ClaimTask
	mock.lockClaimTask.RUnlock()
	return calls
}

// CountEventsByJobNumber calls CountEventsByJobNumberFunc.
func (mock *JobServiceMock) CountEventsByJobNumber(ctx context.Context, jobNumber int) (int, error) {
	if mock.CountEventsByJobNumberFunc == nil {
		panic("JobServiceMock.CountEventsByJobNumberFunc: method is nil but JobService.CountEventsByJobNumber was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		JobNumber int
	}{
		Ctx:       ctx,
		JobNumber: jobNumber,
	}
	mock.lockCountEventsByJobNumber.Lock()
	mock.calls.CountEventsByJobNumber = append(mock.calls.CountEventsByJobNumber, callInfo)
	mock.lockCountEventsByJobNumber.Unlock()
	return mock.CountEventsByJobNumberFunc(ctx, jobNumber)
}

// CountEventsByJobNumberCalls gets all the calls that were made to CountEventsByJobNumber.
// Check the length with:
//     len(mockedJobService.CountEventsByJobNumberCalls())
func (mock *JobServiceMock) CountEventsByJobNumberCalls() []struct {
	Ctx       context.Context
	JobNumber int
} {
	var calls []struct {
		Ctx       context.Context
		JobNumber int
	}
	mock.lockCountEventsByJobNumber.RLock()
	calls = mock.calls.CountEventsByJobNumber
	mock.lockCountEventsByJobNumber.RUnlock()
	return calls
}

// CountTasksByJobNumber calls CountTasksByJobNumberFunc.
func (mock *JobServiceMock) CountTasksByJobNumber(ctx context.Context, jobNumber int) (int, error) {
	if mock.CountTasksByJobNumberFunc == nil {
		panic("JobServiceMock.CountTasksByJobNumberFunc: method is nil but JobService.CountTasksByJobNumber was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		JobNumber int
	}{
		Ctx:       ctx,
		JobNumber: jobNumber,
	}
	mock.lockCountTasksByJobNumber.Lock()
	mock.calls.CountTasksByJobNumber = append(mock.calls.CountTasksByJobNumber, callInfo)
	mock.lockCountTasksByJobNumber.Unlock()
	return mock.CountTasksByJobNumberFunc(ctx, jobNumber)
}

// CountTasksByJobNumberCalls gets all the calls that were made to CountTasksByJobNumber.
// Check the length with:
//     len(mockedJobService.CountTasksByJobNumberCalls())
func (mock *JobServiceMock) CountTasksByJobNumberCalls() []struct {
	Ctx       context.Context
	JobNumber int
} {
	var calls []struct {
		Ctx       context.Context
		JobNumber int
	}
	mock.lockCountTasksByJobNumber.RLock()
	calls = mock.calls.CountTasksByJobNumber
	mock.lockCountTasksByJobNumber.RUnlock()
	return calls
}

// CreateEvent calls CreateEventFunc.
func (mock *JobServiceMock) CreateEvent(ctx context.Context, jobNumber int, event *domain.Event) (*domain.Event, error) {
	if mock.CreateEventFunc == nil {
		panic("JobServiceMock.CreateEventFunc: method is nil but JobService.CreateEvent was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		JobNumber int
		Event     *domain.Event
	}{
		Ctx:       ctx,
		JobNumber: jobNumber,
		Event:     event,
	}
	mock.lockCreateEvent.Lock()
	mock.calls.CreateEvent = append(mock.calls.CreateEvent, callInfo)
	mock.lockCreateEvent.Unlock()
	return mock.CreateEventFunc(ctx, jobNumber, event)
}

// CreateEventCalls gets all the calls that were made to CreateEvent.
// Check the length with:
//     len(mockedJobService.CreateEventCalls())
func (mock *JobServiceMock) CreateEventCalls() []struct {
	Ctx       context.Context
	JobNumber int
	Event     *domain.Event
} {
	var calls []struct {
		Ctx       context.Context
		JobNumber int
		Event     *domain.Event
	}
	mock.lockCreateEvent.RLock()
	calls = mock.calls.CreateEvent
	mock.lockCreateEvent.RUnlock()
	return calls
}

// CreateJob calls CreateJobFunc.
func (mock *JobServiceMock) CreateJob(ctx context.Context, jobConfig *domain.JobConfig) (*domain.Job, error) {
	if mock.CreateJobFunc == nil {
		panic("JobServiceMock.CreateJobFunc: method is nil but JobService.CreateJob was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		JobConfig *domain.JobConfig
	}{
		Ctx:       ctx,
		JobConfig: jobConfig,
	}
	mock.lockCreateJob.Lock()
	mock.calls.CreateJob = append(mock.calls.CreateJob, callInfo)
	mock.lockCreateJob.Unlock()
	return mock.CreateJobFunc(ctx, jobConfig)
}

// CreateJobCalls gets all the calls that were made to CreateJob.
// Check the length with:
//     len(mockedJobService.CreateJobCalls())
func (mock *JobServiceMock) CreateJobCalls() []struct {
	Ctx       context.Context
	JobConfig *domain.JobConfig
} {
	var calls []struct {
		Ctx       context.Context
		JobConfig *domain.JobConfig
	}
	mock.lockCreateJob.RLock()
	calls = mock.calls.CreateJob
	mock.lockCreateJob.RUnlock()
	return calls
}

// CreateTask calls CreateTaskFunc.
func (mock *JobServiceMock) CreateTask(ctx context.Context, jobNumber int, task *domain.Task) (*domain.Task, error) {
	if mock.CreateTaskFunc == nil {
		panic("JobServiceMock.CreateTaskFunc: method is nil but JobService.CreateTask was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		JobNumber int
		Task      *domain.Task
	}{
		Ctx:       ctx,
		JobNumber: jobNumber,
		Task:      task,
	}
	mock.lockCreateTask.Lock()
	mock.calls.CreateTask = append(mock.calls.CreateTask, callInfo)
	mock.lockCreateTask.Unlock()
	return mock.CreateTaskFunc(ctx, jobNumber, task)
}

// CreateTaskCalls gets all the calls that were made to CreateTask.
// Check the length with:
//     len(mockedJobService.CreateTaskCalls())
func (mock *JobServiceMock) CreateTaskCalls() []struct {
	Ctx       context.Context
	JobNumber int
	Task      *domain.Task
} {
	var calls []struct {
		Ctx       context.Context
		JobNumber int
		Task      *domain.Task
	}
	mock.lockCreateTask.RLock()
	calls = mock.calls.CreateTask
	mock.lockCreateTask.RUnlock()
	return calls
}

// GetJob calls GetJobFunc.
func (mock *JobServiceMock) GetJob(ctx context.Context, jobNumber int) (*domain.Job, error) {
	if mock.GetJobFunc == nil {
		panic("JobServiceMock.GetJobFunc: method is nil but JobService.GetJob was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		JobNumber int
	}{
		Ctx:       ctx,
		JobNumber: jobNumber,
	}
	mock.lockGetJob.Lock()
	mock.calls.GetJob = append(mock.calls.GetJob, callInfo)
	mock.lockGetJob.Unlock()
	return mock.GetJobFunc(ctx, jobNumber)
}

// GetJobCalls gets all the calls that were made to GetJob.
// Check the length with:
//     len(mockedJobService.GetJobCalls())
func (mock *JobServiceMock) GetJobCalls() []struct {
	Ctx       context.Context
	JobNumber int
} {
	var calls []struct {
		Ctx       context.Context
		JobNumber int
	}
	mock.lockGetJob.RLock()
	calls = mock.calls.GetJob
	mock.lockGetJob.RUnlock()
	return calls
}

// GetJobEvents calls GetJobEventsFunc.
func (mock *JobServiceMock) GetJobEvents(ctx context.Context, jobNumber int, limit int, offset int) ([]*domain.Event, int, error) {
	if mock.GetJobEventsFunc == nil {
		panic("JobServiceMock.GetJobEventsFunc: method is nil but JobService.GetJobEvents was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		JobNumber int
		Limit     int
		Offset    int
	}{
		Ctx:       ctx,
		JobNumber: jobNumber,
		Limit:     limit,
		Offset:    offset,
	}
	mock.lockGetJobEvents.Lock()
	mock.calls.GetJobEvents = append(mock.calls.GetJobEvents, callInfo)
	mock.lockGetJobEvents.Unlock()
	return mock.GetJobEventsFunc(ctx, jobNumber, limit, offset)
}

// GetJobEventsCalls gets all the calls that were made to GetJobEvents.
// Check the length with:
//     len(mockedJobService.GetJobEventsCalls())
func (mock *JobServiceMock) GetJobEventsCalls() []struct {
	Ctx       context.Context
	JobNumber int
	Limit     int
	Offset    int
} {
	var calls []struct {
		Ctx       context.Context
		JobNumber int
		Limit     int
		Offset    int
	}
	mock.lockGetJobEvents.RLock()
	calls = mock.calls.GetJobEvents
	mock.lockGetJobEvents.RUnlock()
	return calls
}

// GetJobNumberCounter calls GetJobNumberCounterFunc.
func (mock *JobServiceMock) GetJobNumberCounter(ctx context.Context) (*domain.Counter, error) {
	if mock.GetJobNumberCounterFunc == nil {
		panic("JobServiceMock.GetJobNumberCounterFunc: method is nil but JobService.GetJobNumberCounter was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetJobNumberCounter.Lock()
	mock.calls.GetJobNumberCounter = append(mock.calls.GetJobNumberCounter, callInfo)
	mock.lockGetJobNumberCounter.Unlock()
	return mock.GetJobNumberCounterFunc(ctx)
}

// GetJobNumberCounterCalls gets all the calls that were made to GetJobNumberCounter.
// Check the length with:
//     len(mockedJobService.GetJobNumberCounterCalls())
func (mock *JobServiceMock) GetJobNumberCounterCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetJobNumberCounter.RLock()
	calls = mock.calls.GetJobNumberCounter
	mock.lockGetJobNumberCounter.RUnlock()
	return calls
}

// GetJobTasks calls GetJobTasksFunc.
func (mock *JobServiceMock) GetJobTasks(ctx context.Context, states []domain.TaskState, jobNumber int, limit int, offset int) ([]*domain.Task, int, error) {
	if mock.GetJobTasksFunc == nil {
		panic("JobServiceMock.GetJobTasksFunc: method is nil but JobService.GetJobTasks was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		States    []domain.TaskState
		JobNumber int
		Limit     int
		Offset    int
	}{
		Ctx:       ctx,
		States:    states,
		JobNumber: jobNumber,
		Limit:     limit,
		Offset:    offset,
	}
	mock.lockGetJobTasks.Lock()
	mock.calls.GetJobTasks = append(mock.calls.GetJobTasks, callInfo)
	mock.lockGetJobTasks.Unlock()
	return mock.GetJobTasksFunc(ctx, states, jobNumber, limit, offset)
}

// GetJobTasksCalls gets all the calls that were made to GetJobTasks.
// Check the length with:
//     len(mockedJobService.GetJobTasksCalls())
func (mock *JobServiceMock) GetJobTasksCalls() []struct {
	Ctx       context.Context
	States    []domain.TaskState
	JobNumber int
	Limit     int
	Offset    int
} {
	var calls []struct {
		Ctx       context.Context
		States    []domain.TaskState
		JobNumber int
		Limit     int
		Offset    int
	}
	mock.lockGetJobTasks.RLock()
	calls = mock.calls.GetJobTasks
	mock.lockGetJobTasks.RUnlock()
	return calls
}

// GetJobs calls GetJobsFunc.
func (mock *JobServiceMock) GetJobs(ctx context.Context, states []domain.JobState, limit int, offset int) ([]*domain.Job, int, error) {
	if mock.GetJobsFunc == nil {
		panic("JobServiceMock.GetJobsFunc: method is nil but JobService.GetJobs was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		States []domain.JobState
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		States: states,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockGetJobs.Lock()
	mock.calls.GetJobs = append(mock.calls.GetJobs, callInfo)
	mock.lockGetJobs.Unlock()
	return mock.GetJobsFunc(ctx, states, limit, offset)
}

// GetJobsCalls gets all the calls that were made to GetJobs.
// Check the length with:
//     len(mockedJobService.GetJobsCalls())
func (mock *JobServiceMock) GetJobsCalls() []struct {
	Ctx    context.Context
	States []domain.JobState
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		States []domain.JobState
		Limit  int
		Offset int
	}
	mock.lockGetJobs.RLock()
	calls = mock.calls.GetJobs
	mock.lockGetJobs.RUnlock()
	return calls
}

// GetNextJobNumberCounter calls GetNextJobNumberCounterFunc.
func (mock *JobServiceMock) GetNextJobNumberCounter(ctx context.Context) (*domain.Counter, error) {
	if mock.GetNextJobNumberCounterFunc == nil {
		panic("JobServiceMock.GetNextJobNumberCounterFunc: method is nil but JobService.GetNextJobNumberCounter was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetNextJobNumberCounter.Lock()
	mock.calls.GetNextJobNumberCounter = append(mock.calls.GetNextJobNumberCounter, callInfo)
	mock.lockGetNextJobNumberCounter.Unlock()
	return mock.GetNextJobNumberCounterFunc(ctx)
}

// GetNextJobNumberCounterCalls gets all the calls that were made to GetNextJobNumberCounter.
// Check the length with:
//     len(mockedJobService.GetNextJobNumberCounterCalls())
func (mock *JobServiceMock) GetNextJobNumberCounterCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetNextJobNumberCounter.RLock()
	calls = mock.calls.GetNextJobNumberCounter
	mock.lockGetNextJobNumberCounter.RUnlock()
	return calls
}

// UpdateJobState calls UpdateJobStateFunc.
func (mock *JobServiceMock) UpdateJobState(ctx context.Context, jobNumber int, newState domain.JobState) error {
	if mock.UpdateJobStateFunc == nil {
		panic("JobServiceMock.UpdateJobStateFunc: method is nil but JobService.UpdateJobState was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		JobNumber int
		NewState  domain.JobState
	}{
		Ctx:       ctx,
		JobNumber: jobNumber,
		NewState:  newState,
	}
	mock.lockUpdateJobState.Lock()
	mock.calls.UpdateJobState = append(mock.calls.UpdateJobState, callInfo)
	mock.lockUpdateJobState.Unlock()
	return mock.UpdateJobStateFunc(ctx, jobNumber, newState)
}

// UpdateJobStateCalls gets all the calls that were made to UpdateJobState.
// Check the length with:
//     len(mockedJobService.UpdateJobStateCalls())
func (mock *JobServiceMock) UpdateJobStateCalls() []struct {
	Ctx       context.Context
	JobNumber int
	NewState  domain.JobState
} {
	var calls []struct {
		Ctx       context.Context
		JobNumber int
		NewState  domain.JobState
	}
	mock.lockUpdateJobState.RLock()
	calls = mock.calls.UpdateJobState
	mock.lockUpdateJobState.RUnlock()
	return calls
}

// UpdateTask calls UpdateTaskFunc.
func (mock *JobServiceMock) UpdateTask(ctx context.Context, task *domain.Task) error {
	if mock.UpdateTaskFunc == nil {
		panic("JobServiceMock.UpdateTaskFunc: method is nil but JobService.UpdateTask was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Task *domain.Task
	}{
		Ctx:  ctx,
		Task: task,
	}
	mock.lockUpdateTask.Lock()
	mock.calls.UpdateTask = append(mock.calls.UpdateTask, callInfo)
	mock.lockUpdateTask.Unlock()
	return mock.UpdateTaskFunc(ctx, task)
}

// UpdateTaskCalls gets all the calls that were made to UpdateTask.
// Check the length with:
//     len(mockedJobService.UpdateTaskCalls())
func (mock *JobServiceMock) UpdateTaskCalls() []struct {
	Ctx  context.Context
	Task *domain.Task
} {
	var calls []struct {
		Ctx  context.Context
		Task *domain.Task
	}
	mock.lockUpdateTask.RLock()
	calls = mock.calls.UpdateTask
	mock.lockUpdateTask.RUnlock()
	return calls
}

// UpdateTaskState calls UpdateTaskStateFunc.
func (mock *JobServiceMock) UpdateTaskState(ctx context.Context, taskID string, newState domain.TaskState) error {
	if mock.UpdateTaskStateFunc == nil {
		panic("JobServiceMock.UpdateTaskStateFunc: method is nil but JobService.UpdateTaskState was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		TaskID   string
		NewState domain.TaskState
	}{
		Ctx:      ctx,
		TaskID:   taskID,
		NewState: newState,
	}
	mock.lockUpdateTaskState.Lock()
	mock.calls.UpdateTaskState = append(mock.calls.UpdateTaskState, callInfo)
	mock.lockUpdateTaskState.Unlock()
	return mock.UpdateTaskStateFunc(ctx, taskID, newState)
}

// UpdateTaskStateCalls gets all the calls that were made to UpdateTaskState.
// Check the length with:
//     len(mockedJobService.UpdateTaskStateCalls())
func (mock *JobServiceMock) UpdateTaskStateCalls() []struct {
	Ctx      context.Context
	TaskID   string
	NewState domain.TaskState
} {
	var calls []struct {
		Ctx      context.Context
		TaskID   string
		NewState domain.TaskState
	}
	mock.lockUpdateTaskState.RLock()
	calls = mock.calls.UpdateTaskState
	mock.lockUpdateTaskState.RUnlock()
	return calls
}
