// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-migration-service/clients"
	"github.com/ONSdigital/dis-migration-service/domain"
	"sync"
)

// Ensure, that JobValidatorMock does implement domain.JobValidator.
// If this is not the case, regenerate this file with moq.
var _ domain.JobValidator = &JobValidatorMock{}

// JobValidatorMock is a mock implementation of domain.JobValidator.
//
//	func TestSomethingThatUsesJobValidator(t *testing.T) {
//
//		// make and configure a mocked domain.JobValidator
//		mockedJobValidator := &JobValidatorMock{
//			ValidateSourceIDFunc: func(sourceID string) error {
//				panic("mock out the ValidateSourceID method")
//			},
//			ValidateSourceIDWithExternalFunc: func(ctx context.Context, sourceID string, appClients *clients.ClientList) (string, error) {
//				panic("mock out the ValidateSourceIDWithExternal method")
//			},
//			ValidateTargetIDFunc: func(targetID string) error {
//				panic("mock out the ValidateTargetID method")
//			},
//			ValidateTargetIDWithExternalFunc: func(ctx context.Context, targetID string, appClients *clients.ClientList) error {
//				panic("mock out the ValidateTargetIDWithExternal method")
//			},
//		}
//
//		// use mockedJobValidator in code that requires domain.JobValidator
//		// and then make assertions.
//
//	}
type JobValidatorMock struct {
	// ValidateSourceIDFunc mocks the ValidateSourceID method.
	ValidateSourceIDFunc func(sourceID string) error

	// ValidateSourceIDWithExternalFunc mocks the ValidateSourceIDWithExternal method.
	ValidateSourceIDWithExternalFunc func(ctx context.Context, sourceID string, appClients *clients.ClientList) (string, error)

	// ValidateTargetIDFunc mocks the ValidateTargetID method.
	ValidateTargetIDFunc func(targetID string) error

	// ValidateTargetIDWithExternalFunc mocks the ValidateTargetIDWithExternal method.
	ValidateTargetIDWithExternalFunc func(ctx context.Context, targetID string, appClients *clients.ClientList) error

	// calls tracks calls to the methods.
	calls struct {
		// ValidateSourceID holds details about calls to the ValidateSourceID method.
		ValidateSourceID []struct {
			// SourceID is the sourceID argument value.
			SourceID string
		}
		// ValidateSourceIDWithExternal holds details about calls to the ValidateSourceIDWithExternal method.
		ValidateSourceIDWithExternal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// SourceID is the sourceID argument value.
			SourceID string
			// AppClients is the appClients argument value.
			AppClients *clients.ClientList
		}
		// ValidateTargetID holds details about calls to the ValidateTargetID method.
		ValidateTargetID []struct {
			// TargetID is the targetID argument value.
			TargetID string
		}
		// ValidateTargetIDWithExternal holds details about calls to the ValidateTargetIDWithExternal method.
		ValidateTargetIDWithExternal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TargetID is the targetID argument value.
			TargetID string
			// AppClients is the appClients argument value.
			AppClients *clients.ClientList
		}
	}
	lockValidateSourceID             sync.RWMutex
	lockValidateSourceIDWithExternal sync.RWMutex
	lockValidateTargetID             sync.RWMutex
	lockValidateTargetIDWithExternal sync.RWMutex
}

// ValidateSourceID calls ValidateSourceIDFunc.
func (mock *JobValidatorMock) ValidateSourceID(sourceID string) error {
	if mock.ValidateSourceIDFunc == nil {
		panic("JobValidatorMock.ValidateSourceIDFunc: method is nil but JobValidator.ValidateSourceID was just called")
	}
	callInfo := struct {
		SourceID string
	}{
		SourceID: sourceID,
	}
	mock.lockValidateSourceID.Lock()
	mock.calls.ValidateSourceID = append(mock.calls.ValidateSourceID, callInfo)
	mock.lockValidateSourceID.Unlock()
	return mock.ValidateSourceIDFunc(sourceID)
}

// ValidateSourceIDCalls gets all the calls that were made to ValidateSourceID.
// Check the length with:
//
//	len(mockedJobValidator.ValidateSourceIDCalls())
func (mock *JobValidatorMock) ValidateSourceIDCalls() []struct {
	SourceID string
} {
	var calls []struct {
		SourceID string
	}
	mock.lockValidateSourceID.RLock()
	calls = mock.calls.ValidateSourceID
	mock.lockValidateSourceID.RUnlock()
	return calls
}

// ValidateSourceIDWithExternal calls ValidateSourceIDWithExternalFunc.
func (mock *JobValidatorMock) ValidateSourceIDWithExternal(ctx context.Context, sourceID string, appClients *clients.ClientList) (string, error) {
	if mock.ValidateSourceIDWithExternalFunc == nil {
		panic("JobValidatorMock.ValidateSourceIDWithExternalFunc: method is nil but JobValidator.ValidateSourceIDWithExternal was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		SourceID   string
		AppClients *clients.ClientList
	}{
		Ctx:        ctx,
		SourceID:   sourceID,
		AppClients: appClients,
	}
	mock.lockValidateSourceIDWithExternal.Lock()
	mock.calls.ValidateSourceIDWithExternal = append(mock.calls.ValidateSourceIDWithExternal, callInfo)
	mock.lockValidateSourceIDWithExternal.Unlock()
	return mock.ValidateSourceIDWithExternalFunc(ctx, sourceID, appClients)
}

// ValidateSourceIDWithExternalCalls gets all the calls that were made to ValidateSourceIDWithExternal.
// Check the length with:
//
//	len(mockedJobValidator.ValidateSourceIDWithExternalCalls())
func (mock *JobValidatorMock) ValidateSourceIDWithExternalCalls() []struct {
	Ctx        context.Context
	SourceID   string
	AppClients *clients.ClientList
} {
	var calls []struct {
		Ctx        context.Context
		SourceID   string
		AppClients *clients.ClientList
	}
	mock.lockValidateSourceIDWithExternal.RLock()
	calls = mock.calls.ValidateSourceIDWithExternal
	mock.lockValidateSourceIDWithExternal.RUnlock()
	return calls
}

// ValidateTargetID calls ValidateTargetIDFunc.
func (mock *JobValidatorMock) ValidateTargetID(targetID string) error {
	if mock.ValidateTargetIDFunc == nil {
		panic("JobValidatorMock.ValidateTargetIDFunc: method is nil but JobValidator.ValidateTargetID was just called")
	}
	callInfo := struct {
		TargetID string
	}{
		TargetID: targetID,
	}
	mock.lockValidateTargetID.Lock()
	mock.calls.ValidateTargetID = append(mock.calls.ValidateTargetID, callInfo)
	mock.lockValidateTargetID.Unlock()
	return mock.ValidateTargetIDFunc(targetID)
}

// ValidateTargetIDCalls gets all the calls that were made to ValidateTargetID.
// Check the length with:
//
//	len(mockedJobValidator.ValidateTargetIDCalls())
func (mock *JobValidatorMock) ValidateTargetIDCalls() []struct {
	TargetID string
} {
	var calls []struct {
		TargetID string
	}
	mock.lockValidateTargetID.RLock()
	calls = mock.calls.ValidateTargetID
	mock.lockValidateTargetID.RUnlock()
	return calls
}

// ValidateTargetIDWithExternal calls ValidateTargetIDWithExternalFunc.
func (mock *JobValidatorMock) ValidateTargetIDWithExternal(ctx context.Context, targetID string, appClients *clients.ClientList) error {
	if mock.ValidateTargetIDWithExternalFunc == nil {
		panic("JobValidatorMock.ValidateTargetIDWithExternalFunc: method is nil but JobValidator.ValidateTargetIDWithExternal was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		TargetID   string
		AppClients *clients.ClientList
	}{
		Ctx:        ctx,
		TargetID:   targetID,
		AppClients: appClients,
	}
	mock.lockValidateTargetIDWithExternal.Lock()
	mock.calls.ValidateTargetIDWithExternal = append(mock.calls.ValidateTargetIDWithExternal, callInfo)
	mock.lockValidateTargetIDWithExternal.Unlock()
	return mock.ValidateTargetIDWithExternalFunc(ctx, targetID, appClients)
}

// ValidateTargetIDWithExternalCalls gets all the calls that were made to ValidateTargetIDWithExternal.
// Check the length with:
//
//	len(mockedJobValidator.ValidateTargetIDWithExternalCalls())
func (mock *JobValidatorMock) ValidateTargetIDWithExternalCalls() []struct {
	Ctx        context.Context
	TargetID   string
	AppClients *clients.ClientList
} {
	var calls []struct {
		Ctx        context.Context
		TargetID   string
		AppClients *clients.ClientList
	}
	mock.lockValidateTargetIDWithExternal.RLock()
	calls = mock.calls.ValidateTargetIDWithExternal
	mock.lockValidateTargetIDWithExternal.RUnlock()
	return calls
}
