// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/ONSdigital/dis-migration-service/slack"
	"sync"
)

// Ensure, that ClienterMock does implement slack.Clienter.
// If this is not the case, regenerate this file with moq.
var _ slack.Clienter = &ClienterMock{}

// ClienterMock is a mock implementation of slack.Clienter.
//
//	func TestSomethingThatUsesClienter(t *testing.T) {
//
//		// make and configure a mocked slack.Clienter
//		mockedClienter := &ClienterMock{
//			SendAlarmFunc: func(ctx context.Context, summary string, err error, details slack.SlackDetails) error {
//				panic("mock out the SendAlarm method")
//			},
//			SendInfoFunc: func(ctx context.Context, summary string, details slack.SlackDetails) error {
//				panic("mock out the SendInfo method")
//			},
//			SendWarningFunc: func(ctx context.Context, summary string, details slack.SlackDetails) error {
//				panic("mock out the SendWarning method")
//			},
//		}
//
//		// use mockedClienter in code that requires slack.Clienter
//		// and then make assertions.
//
//	}
type ClienterMock struct {
	// SendAlarmFunc mocks the SendAlarm method.
	SendAlarmFunc func(ctx context.Context, summary string, err error, details slack.SlackDetails) error

	// SendInfoFunc mocks the SendInfo method.
	SendInfoFunc func(ctx context.Context, summary string, details slack.SlackDetails) error

	// SendWarningFunc mocks the SendWarning method.
	SendWarningFunc func(ctx context.Context, summary string, details slack.SlackDetails) error

	// calls tracks calls to the methods.
	calls struct {
		// SendAlarm holds details about calls to the SendAlarm method.
		SendAlarm []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Summary is the summary argument value.
			Summary string
			// Err is the err argument value.
			Err error
			// Details is the details argument value.
			Details slack.SlackDetails
		}
		// SendInfo holds details about calls to the SendInfo method.
		SendInfo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Summary is the summary argument value.
			Summary string
			// Details is the details argument value.
			Details slack.SlackDetails
		}
		// SendWarning holds details about calls to the SendWarning method.
		SendWarning []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Summary is the summary argument value.
			Summary string
			// Details is the details argument value.
			Details slack.SlackDetails
		}
	}
	lockSendAlarm   sync.RWMutex
	lockSendInfo    sync.RWMutex
	lockSendWarning sync.RWMutex
}

// SendAlarm calls SendAlarmFunc.
func (mock *ClienterMock) SendAlarm(ctx context.Context, summary string, err error, details slack.SlackDetails) error {
	if mock.SendAlarmFunc == nil {
		panic("ClienterMock.SendAlarmFunc: method is nil but Clienter.SendAlarm was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Summary string
		Err     error
		Details slack.SlackDetails
	}{
		Ctx:     ctx,
		Summary: summary,
		Err:     err,
		Details: details,
	}
	mock.lockSendAlarm.Lock()
	mock.calls.SendAlarm = append(mock.calls.SendAlarm, callInfo)
	mock.lockSendAlarm.Unlock()
	return mock.SendAlarmFunc(ctx, summary, err, details)
}

// SendAlarmCalls gets all the calls that were made to SendAlarm.
// Check the length with:
//
//	len(mockedClienter.SendAlarmCalls())
func (mock *ClienterMock) SendAlarmCalls() []struct {
	Ctx     context.Context
	Summary string
	Err     error
	Details slack.SlackDetails
} {
	var calls []struct {
		Ctx     context.Context
		Summary string
		Err     error
		Details slack.SlackDetails
	}
	mock.lockSendAlarm.RLock()
	calls = mock.calls.SendAlarm
	mock.lockSendAlarm.RUnlock()
	return calls
}

// SendInfo calls SendInfoFunc.
func (mock *ClienterMock) SendInfo(ctx context.Context, summary string, details slack.SlackDetails) error {
	if mock.SendInfoFunc == nil {
		panic("ClienterMock.SendInfoFunc: method is nil but Clienter.SendInfo was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Summary string
		Details slack.SlackDetails
	}{
		Ctx:     ctx,
		Summary: summary,
		Details: details,
	}
	mock.lockSendInfo.Lock()
	mock.calls.SendInfo = append(mock.calls.SendInfo, callInfo)
	mock.lockSendInfo.Unlock()
	return mock.SendInfoFunc(ctx, summary, details)
}

// SendInfoCalls gets all the calls that were made to SendInfo.
// Check the length with:
//
//	len(mockedClienter.SendInfoCalls())
func (mock *ClienterMock) SendInfoCalls() []struct {
	Ctx     context.Context
	Summary string
	Details slack.SlackDetails
} {
	var calls []struct {
		Ctx     context.Context
		Summary string
		Details slack.SlackDetails
	}
	mock.lockSendInfo.RLock()
	calls = mock.calls.SendInfo
	mock.lockSendInfo.RUnlock()
	return calls
}

// SendWarning calls SendWarningFunc.
func (mock *ClienterMock) SendWarning(ctx context.Context, summary string, details slack.SlackDetails) error {
	if mock.SendWarningFunc == nil {
		panic("ClienterMock.SendWarningFunc: method is nil but Clienter.SendWarning was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Summary string
		Details slack.SlackDetails
	}{
		Ctx:     ctx,
		Summary: summary,
		Details: details,
	}
	mock.lockSendWarning.Lock()
	mock.calls.SendWarning = append(mock.calls.SendWarning, callInfo)
	mock.lockSendWarning.Unlock()
	return mock.SendWarningFunc(ctx, summary, details)
}

// SendWarningCalls gets all the calls that were made to SendWarning.
// Check the length with:
//
//	len(mockedClienter.SendWarningCalls())
func (mock *ClienterMock) SendWarningCalls() []struct {
	Ctx     context.Context
	Summary string
	Details slack.SlackDetails
} {
	var calls []struct {
		Ctx     context.Context
		Summary string
		Details slack.SlackDetails
	}
	mock.lockSendWarning.RLock()
	calls = mock.calls.SendWarning
	mock.lockSendWarning.RUnlock()
	return calls
}
