// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-migration-service/domain"
	"github.com/ONSdigital/dis-migration-service/store"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"sync"
)

// Ensure, that MongoDBMock does implement store.MongoDB.
// If this is not the case, regenerate this file with moq.
var _ store.MongoDB = &MongoDBMock{}

// MongoDBMock is a mock implementation of store.MongoDB.
//
//	func TestSomethingThatUsesMongoDB(t *testing.T) {
//
//		// make and configure a mocked store.MongoDB
//		mockedMongoDB := &MongoDBMock{
//			CheckerFunc: func(contextMoqParam context.Context, checkState *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			CloseFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Close method")
//			},
//			CreateEventFunc: func(ctx context.Context, event *domain.Event) error {
//				panic("mock out the CreateEvent method")
//			},
//			CreateJobFunc: func(ctx context.Context, job *domain.Job) error {
//				panic("mock out the CreateJob method")
//			},
//			GetJobFunc: func(ctx context.Context, jobID string) (*domain.Job, error) {
//				panic("mock out the GetJob method")
//			},
//			GetJobsByConfigAndStateFunc: func(ctx context.Context, jc *domain.JobConfig, states []domain.JobState, limit int, offset int) ([]*domain.Job, error) {
//				panic("mock out the GetJobsByConfigAndState method")
//			},
//		}
//
//		// use mockedMongoDB in code that requires store.MongoDB
//		// and then make assertions.
//
//	}
type MongoDBMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(contextMoqParam context.Context, checkState *healthcheck.CheckState) error

	// CloseFunc mocks the Close method.
	CloseFunc func(contextMoqParam context.Context) error

	// CreateEventFunc mocks the CreateEvent method.
	CreateEventFunc func(ctx context.Context, event *domain.Event) error

	// CreateJobFunc mocks the CreateJob method.
	CreateJobFunc func(ctx context.Context, job *domain.Job) error

	// GetJobFunc mocks the GetJob method.
	GetJobFunc func(ctx context.Context, jobID string) (*domain.Job, error)

	// GetJobsByConfigAndStateFunc mocks the GetJobsByConfigAndState method.
	GetJobsByConfigAndStateFunc func(ctx context.Context, jc *domain.JobConfig, states []domain.JobState, limit int, offset int) ([]*domain.Job, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// CheckState is the checkState argument value.
			CheckState *healthcheck.CheckState
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// CreateEvent holds details about calls to the CreateEvent method.
		CreateEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *domain.Event
		}
		// CreateJob holds details about calls to the CreateJob method.
		CreateJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Job is the job argument value.
			Job *domain.Job
		}
		// GetJob holds details about calls to the GetJob method.
		GetJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
		}
		// GetJobsByConfigAndState holds details about calls to the GetJobsByConfigAndState method.
		GetJobsByConfigAndState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Jc is the jc argument value.
			Jc *domain.JobConfig
			// States is the states argument value.
			States []domain.JobState
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
	}
	lockChecker                 sync.RWMutex
	lockClose                   sync.RWMutex
	lockCreateEvent             sync.RWMutex
	lockCreateJob               sync.RWMutex
	lockGetJob                  sync.RWMutex
	lockGetJobsByConfigAndState sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *MongoDBMock) Checker(contextMoqParam context.Context, checkState *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("MongoDBMock.CheckerFunc: method is nil but MongoDB.Checker was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		CheckState      *healthcheck.CheckState
	}{
		ContextMoqParam: contextMoqParam,
		CheckState:      checkState,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(contextMoqParam, checkState)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedMongoDB.CheckerCalls())
func (mock *MongoDBMock) CheckerCalls() []struct {
	ContextMoqParam context.Context
	CheckState      *healthcheck.CheckState
} {
	var calls []struct {
		ContextMoqParam context.Context
		CheckState      *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *MongoDBMock) Close(contextMoqParam context.Context) error {
	if mock.CloseFunc == nil {
		panic("MongoDBMock.CloseFunc: method is nil but MongoDB.Close was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc(contextMoqParam)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedMongoDB.CloseCalls())
func (mock *MongoDBMock) CloseCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CreateEvent calls CreateEventFunc.
func (mock *MongoDBMock) CreateEvent(ctx context.Context, event *domain.Event) error {
	if mock.CreateEventFunc == nil {
		panic("MongoDBMock.CreateEventFunc: method is nil but MongoDB.CreateEvent was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *domain.Event
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockCreateEvent.Lock()
	mock.calls.CreateEvent = append(mock.calls.CreateEvent, callInfo)
	mock.lockCreateEvent.Unlock()
	return mock.CreateEventFunc(ctx, event)
}

// CreateEventCalls gets all the calls that were made to CreateEvent.
// Check the length with:
//
//	len(mockedMongoDB.CreateEventCalls())
func (mock *MongoDBMock) CreateEventCalls() []struct {
	Ctx   context.Context
	Event *domain.Event
} {
	var calls []struct {
		Ctx   context.Context
		Event *domain.Event
	}
	mock.lockCreateEvent.RLock()
	calls = mock.calls.CreateEvent
	mock.lockCreateEvent.RUnlock()
	return calls
}

// CreateJob calls CreateJobFunc.
func (mock *MongoDBMock) CreateJob(ctx context.Context, job *domain.Job) error {
	if mock.CreateJobFunc == nil {
		panic("MongoDBMock.CreateJobFunc: method is nil but MongoDB.CreateJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Job *domain.Job
	}{
		Ctx: ctx,
		Job: job,
	}
	mock.lockCreateJob.Lock()
	mock.calls.CreateJob = append(mock.calls.CreateJob, callInfo)
	mock.lockCreateJob.Unlock()
	return mock.CreateJobFunc(ctx, job)
}

// CreateJobCalls gets all the calls that were made to CreateJob.
// Check the length with:
//
//	len(mockedMongoDB.CreateJobCalls())
func (mock *MongoDBMock) CreateJobCalls() []struct {
	Ctx context.Context
	Job *domain.Job
} {
	var calls []struct {
		Ctx context.Context
		Job *domain.Job
	}
	mock.lockCreateJob.RLock()
	calls = mock.calls.CreateJob
	mock.lockCreateJob.RUnlock()
	return calls
}

// GetJob calls GetJobFunc.
func (mock *MongoDBMock) GetJob(ctx context.Context, jobID string) (*domain.Job, error) {
	if mock.GetJobFunc == nil {
		panic("MongoDBMock.GetJobFunc: method is nil but MongoDB.GetJob was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		JobID string
	}{
		Ctx:   ctx,
		JobID: jobID,
	}
	mock.lockGetJob.Lock()
	mock.calls.GetJob = append(mock.calls.GetJob, callInfo)
	mock.lockGetJob.Unlock()
	return mock.GetJobFunc(ctx, jobID)
}

// GetJobCalls gets all the calls that were made to GetJob.
// Check the length with:
//
//	len(mockedMongoDB.GetJobCalls())
func (mock *MongoDBMock) GetJobCalls() []struct {
	Ctx   context.Context
	JobID string
} {
	var calls []struct {
		Ctx   context.Context
		JobID string
	}
	mock.lockGetJob.RLock()
	calls = mock.calls.GetJob
	mock.lockGetJob.RUnlock()
	return calls
}

// GetJobsByConfigAndState calls GetJobsByConfigAndStateFunc.
func (mock *MongoDBMock) GetJobsByConfigAndState(ctx context.Context, jc *domain.JobConfig, states []domain.JobState, limit int, offset int) ([]*domain.Job, error) {
	if mock.GetJobsByConfigAndStateFunc == nil {
		panic("MongoDBMock.GetJobsByConfigAndStateFunc: method is nil but MongoDB.GetJobsByConfigAndState was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Jc     *domain.JobConfig
		States []domain.JobState
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Jc:     jc,
		States: states,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockGetJobsByConfigAndState.Lock()
	mock.calls.GetJobsByConfigAndState = append(mock.calls.GetJobsByConfigAndState, callInfo)
	mock.lockGetJobsByConfigAndState.Unlock()
	return mock.GetJobsByConfigAndStateFunc(ctx, jc, states, limit, offset)
}

// GetJobsByConfigAndStateCalls gets all the calls that were made to GetJobsByConfigAndState.
// Check the length with:
//
//	len(mockedMongoDB.GetJobsByConfigAndStateCalls())
func (mock *MongoDBMock) GetJobsByConfigAndStateCalls() []struct {
	Ctx    context.Context
	Jc     *domain.JobConfig
	States []domain.JobState
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Jc     *domain.JobConfig
		States []domain.JobState
		Limit  int
		Offset int
	}
	mock.lockGetJobsByConfigAndState.RLock()
	calls = mock.calls.GetJobsByConfigAndState
	mock.lockGetJobsByConfigAndState.RUnlock()
	return calls
}
