// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-migration-service/domain"
	"github.com/ONSdigital/dis-migration-service/store"
	"github.com/ONSdigital/dp-healthcheck/healthcheck"
	"sync"
)

// Ensure, that MongoDBMock does implement store.MongoDB.
// If this is not the case, regenerate this file with moq.
var _ store.MongoDB = &MongoDBMock{}

// MongoDBMock is a mock implementation of store.MongoDB.
//
//	func TestSomethingThatUsesMongoDB(t *testing.T) {
//
//		// make and configure a mocked store.MongoDB
//		mockedMongoDB := &MongoDBMock{
//			CheckerFunc: func(contextMoqParam context.Context, checkState *healthcheck.CheckState) error {
//				panic("mock out the Checker method")
//			},
//			CloseFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Close method")
//			},
//			CountEventsByJobIDFunc: func(ctx context.Context, jobID string) (int, error) {
//				panic("mock out the CountEventsByJobID method")
//			},
//			CountTasksByJobIDFunc: func(ctx context.Context, jobID string) (int, error) {
//				panic("mock out the CountTasksByJobID method")
//			},
//			CreateEventFunc: func(ctx context.Context, event *domain.Event) error {
//				panic("mock out the CreateEvent method")
//			},
//			CreateJobFunc: func(ctx context.Context, job *domain.Job) error {
//				panic("mock out the CreateJob method")
//			},
//			CreateTaskFunc: func(ctx context.Context, task *domain.Task) error {
//				panic("mock out the CreateTask method")
//			},
//			GetJobFunc: func(ctx context.Context, jobID string) (*domain.Job, error) {
//				panic("mock out the GetJob method")
//			},
//			GetJobEventsFunc: func(ctx context.Context, jobID string, limit int, offset int) ([]*domain.Event, int, error) {
//				panic("mock out the GetJobEvents method")
//			},
//			GetJobTasksFunc: func(ctx context.Context, jobID string, limit int, offset int) ([]*domain.Task, int, error) {
//				panic("mock out the GetJobTasks method")
//			},
//			GetJobsFunc: func(ctx context.Context, states []domain.JobState, limit int, offset int) ([]*domain.Job, int, error) {
//				panic("mock out the GetJobs method")
//			},
//			GetJobsByConfigAndStateFunc: func(ctx context.Context, jc *domain.JobConfig, states []domain.JobState, limit int, offset int) ([]*domain.Job, error) {
//				panic("mock out the GetJobsByConfigAndState method")
//			},
//		}
//
//		// use mockedMongoDB in code that requires store.MongoDB
//		// and then make assertions.
//
//	}
type MongoDBMock struct {
	// CheckerFunc mocks the Checker method.
	CheckerFunc func(contextMoqParam context.Context, checkState *healthcheck.CheckState) error

	// CloseFunc mocks the Close method.
	CloseFunc func(contextMoqParam context.Context) error

	// CountEventsByJobIDFunc mocks the CountEventsByJobID method.
	CountEventsByJobIDFunc func(ctx context.Context, jobID string) (int, error)

	// CountTasksByJobIDFunc mocks the CountTasksByJobID method.
	CountTasksByJobIDFunc func(ctx context.Context, jobID string) (int, error)

	// CreateEventFunc mocks the CreateEvent method.
	CreateEventFunc func(ctx context.Context, event *domain.Event) error

	// CreateJobFunc mocks the CreateJob method.
	CreateJobFunc func(ctx context.Context, job *domain.Job) error

	// CreateTaskFunc mocks the CreateTask method.
	CreateTaskFunc func(ctx context.Context, task *domain.Task) error

	// GetJobFunc mocks the GetJob method.
	GetJobFunc func(ctx context.Context, jobID string) (*domain.Job, error)

	// GetJobEventsFunc mocks the GetJobEvents method.
	GetJobEventsFunc func(ctx context.Context, jobID string, limit int, offset int) ([]*domain.Event, int, error)

	// GetJobTasksFunc mocks the GetJobTasks method.
	GetJobTasksFunc func(ctx context.Context, jobID string, limit int, offset int) ([]*domain.Task, int, error)

	// GetJobsFunc mocks the GetJobs method.
	GetJobsFunc func(ctx context.Context, states []domain.JobState, limit int, offset int) ([]*domain.Job, int, error)

	// GetJobsByConfigAndStateFunc mocks the GetJobsByConfigAndState method.
	GetJobsByConfigAndStateFunc func(ctx context.Context, jc *domain.JobConfig, states []domain.JobState, limit int, offset int) ([]*domain.Job, error)

	// calls tracks calls to the methods.
	calls struct {
		// Checker holds details about calls to the Checker method.
		Checker []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// CheckState is the checkState argument value.
			CheckState *healthcheck.CheckState
		}
		// Close holds details about calls to the Close method.
		Close []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// CountEventsByJobID holds details about calls to the CountEventsByJobID method.
		CountEventsByJobID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
		}
		// CountTasksByJobID holds details about calls to the CountTasksByJobID method.
		CountTasksByJobID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
		}
		// CreateEvent holds details about calls to the CreateEvent method.
		CreateEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *domain.Event
		}
		// CreateJob holds details about calls to the CreateJob method.
		CreateJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Job is the job argument value.
			Job *domain.Job
		}
		// CreateTask holds details about calls to the CreateTask method.
		CreateTask []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Task is the task argument value.
			Task *domain.Task
		}
		// GetJob holds details about calls to the GetJob method.
		GetJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
		}
		// GetJobEvents holds details about calls to the GetJobEvents method.
		GetJobEvents []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetJobTasks holds details about calls to the GetJobTasks method.
		GetJobTasks []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// JobID is the jobID argument value.
			JobID string
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetJobs holds details about calls to the GetJobs method.
		GetJobs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// States is the states argument value.
			States []domain.JobState
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
		// GetJobsByConfigAndState holds details about calls to the GetJobsByConfigAndState method.
		GetJobsByConfigAndState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Jc is the jc argument value.
			Jc *domain.JobConfig
			// States is the states argument value.
			States []domain.JobState
			// Limit is the limit argument value.
			Limit int
			// Offset is the offset argument value.
			Offset int
		}
	}
	lockChecker                 sync.RWMutex
	lockClose                   sync.RWMutex
	lockCountEventsByJobID      sync.RWMutex
	lockCountTasksByJobID       sync.RWMutex
	lockCreateEvent             sync.RWMutex
	lockCreateJob               sync.RWMutex
	lockCreateTask              sync.RWMutex
	lockGetJob                  sync.RWMutex
	lockGetJobEvents            sync.RWMutex
	lockGetJobTasks             sync.RWMutex
	lockGetJobs                 sync.RWMutex
	lockGetJobsByConfigAndState sync.RWMutex
}

// Checker calls CheckerFunc.
func (mock *MongoDBMock) Checker(contextMoqParam context.Context, checkState *healthcheck.CheckState) error {
	if mock.CheckerFunc == nil {
		panic("MongoDBMock.CheckerFunc: method is nil but MongoDB.Checker was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		CheckState      *healthcheck.CheckState
	}{
		ContextMoqParam: contextMoqParam,
		CheckState:      checkState,
	}
	mock.lockChecker.Lock()
	mock.calls.Checker = append(mock.calls.Checker, callInfo)
	mock.lockChecker.Unlock()
	return mock.CheckerFunc(contextMoqParam, checkState)
}

// CheckerCalls gets all the calls that were made to Checker.
// Check the length with:
//
//	len(mockedMongoDB.CheckerCalls())
func (mock *MongoDBMock) CheckerCalls() []struct {
	ContextMoqParam context.Context
	CheckState      *healthcheck.CheckState
} {
	var calls []struct {
		ContextMoqParam context.Context
		CheckState      *healthcheck.CheckState
	}
	mock.lockChecker.RLock()
	calls = mock.calls.Checker
	mock.lockChecker.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *MongoDBMock) Close(contextMoqParam context.Context) error {
	if mock.CloseFunc == nil {
		panic("MongoDBMock.CloseFunc: method is nil but MongoDB.Close was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc(contextMoqParam)
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedMongoDB.CloseCalls())
func (mock *MongoDBMock) CloseCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// CountEventsByJobID calls CountEventsByJobIDFunc.
func (mock *MongoDBMock) CountEventsByJobID(ctx context.Context, jobID string) (int, error) {
	if mock.CountEventsByJobIDFunc == nil {
		panic("MongoDBMock.CountEventsByJobIDFunc: method is nil but MongoDB.CountEventsByJobID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		JobID string
	}{
		Ctx:   ctx,
		JobID: jobID,
	}
	mock.lockCountEventsByJobID.Lock()
	mock.calls.CountEventsByJobID = append(mock.calls.CountEventsByJobID, callInfo)
	mock.lockCountEventsByJobID.Unlock()
	return mock.CountEventsByJobIDFunc(ctx, jobID)
}

// CountEventsByJobIDCalls gets all the calls that were made to CountEventsByJobID.
// Check the length with:
//
//	len(mockedMongoDB.CountEventsByJobIDCalls())
func (mock *MongoDBMock) CountEventsByJobIDCalls() []struct {
	Ctx   context.Context
	JobID string
} {
	var calls []struct {
		Ctx   context.Context
		JobID string
	}
	mock.lockCountEventsByJobID.RLock()
	calls = mock.calls.CountEventsByJobID
	mock.lockCountEventsByJobID.RUnlock()
	return calls
}

// CountTasksByJobID calls CountTasksByJobIDFunc.
func (mock *MongoDBMock) CountTasksByJobID(ctx context.Context, jobID string) (int, error) {
	if mock.CountTasksByJobIDFunc == nil {
		panic("MongoDBMock.CountTasksByJobIDFunc: method is nil but MongoDB.CountTasksByJobID was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		JobID string
	}{
		Ctx:   ctx,
		JobID: jobID,
	}
	mock.lockCountTasksByJobID.Lock()
	mock.calls.CountTasksByJobID = append(mock.calls.CountTasksByJobID, callInfo)
	mock.lockCountTasksByJobID.Unlock()
	return mock.CountTasksByJobIDFunc(ctx, jobID)
}

// CountTasksByJobIDCalls gets all the calls that were made to CountTasksByJobID.
// Check the length with:
//
//	len(mockedMongoDB.CountTasksByJobIDCalls())
func (mock *MongoDBMock) CountTasksByJobIDCalls() []struct {
	Ctx   context.Context
	JobID string
} {
	var calls []struct {
		Ctx   context.Context
		JobID string
	}
	mock.lockCountTasksByJobID.RLock()
	calls = mock.calls.CountTasksByJobID
	mock.lockCountTasksByJobID.RUnlock()
	return calls
}

// CreateEvent calls CreateEventFunc.
func (mock *MongoDBMock) CreateEvent(ctx context.Context, event *domain.Event) error {
	if mock.CreateEventFunc == nil {
		panic("MongoDBMock.CreateEventFunc: method is nil but MongoDB.CreateEvent was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *domain.Event
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockCreateEvent.Lock()
	mock.calls.CreateEvent = append(mock.calls.CreateEvent, callInfo)
	mock.lockCreateEvent.Unlock()
	return mock.CreateEventFunc(ctx, event)
}

// CreateEventCalls gets all the calls that were made to CreateEvent.
// Check the length with:
//
//	len(mockedMongoDB.CreateEventCalls())
func (mock *MongoDBMock) CreateEventCalls() []struct {
	Ctx   context.Context
	Event *domain.Event
} {
	var calls []struct {
		Ctx   context.Context
		Event *domain.Event
	}
	mock.lockCreateEvent.RLock()
	calls = mock.calls.CreateEvent
	mock.lockCreateEvent.RUnlock()
	return calls
}

// CreateJob calls CreateJobFunc.
func (mock *MongoDBMock) CreateJob(ctx context.Context, job *domain.Job) error {
	if mock.CreateJobFunc == nil {
		panic("MongoDBMock.CreateJobFunc: method is nil but MongoDB.CreateJob was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Job *domain.Job
	}{
		Ctx: ctx,
		Job: job,
	}
	mock.lockCreateJob.Lock()
	mock.calls.CreateJob = append(mock.calls.CreateJob, callInfo)
	mock.lockCreateJob.Unlock()
	return mock.CreateJobFunc(ctx, job)
}

// CreateJobCalls gets all the calls that were made to CreateJob.
// Check the length with:
//
//	len(mockedMongoDB.CreateJobCalls())
func (mock *MongoDBMock) CreateJobCalls() []struct {
	Ctx context.Context
	Job *domain.Job
} {
	var calls []struct {
		Ctx context.Context
		Job *domain.Job
	}
	mock.lockCreateJob.RLock()
	calls = mock.calls.CreateJob
	mock.lockCreateJob.RUnlock()
	return calls
}

// CreateTask calls CreateTaskFunc.
func (mock *MongoDBMock) CreateTask(ctx context.Context, task *domain.Task) error {
	if mock.CreateTaskFunc == nil {
		panic("MongoDBMock.CreateTaskFunc: method is nil but MongoDB.CreateTask was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Task *domain.Task
	}{
		Ctx:  ctx,
		Task: task,
	}
	mock.lockCreateTask.Lock()
	mock.calls.CreateTask = append(mock.calls.CreateTask, callInfo)
	mock.lockCreateTask.Unlock()
	return mock.CreateTaskFunc(ctx, task)
}

// CreateTaskCalls gets all the calls that were made to CreateTask.
// Check the length with:
//
//	len(mockedMongoDB.CreateTaskCalls())
func (mock *MongoDBMock) CreateTaskCalls() []struct {
	Ctx  context.Context
	Task *domain.Task
} {
	var calls []struct {
		Ctx  context.Context
		Task *domain.Task
	}
	mock.lockCreateTask.RLock()
	calls = mock.calls.CreateTask
	mock.lockCreateTask.RUnlock()
	return calls
}

// GetJob calls GetJobFunc.
func (mock *MongoDBMock) GetJob(ctx context.Context, jobID string) (*domain.Job, error) {
	if mock.GetJobFunc == nil {
		panic("MongoDBMock.GetJobFunc: method is nil but MongoDB.GetJob was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		JobID string
	}{
		Ctx:   ctx,
		JobID: jobID,
	}
	mock.lockGetJob.Lock()
	mock.calls.GetJob = append(mock.calls.GetJob, callInfo)
	mock.lockGetJob.Unlock()
	return mock.GetJobFunc(ctx, jobID)
}

// GetJobCalls gets all the calls that were made to GetJob.
// Check the length with:
//
//	len(mockedMongoDB.GetJobCalls())
func (mock *MongoDBMock) GetJobCalls() []struct {
	Ctx   context.Context
	JobID string
} {
	var calls []struct {
		Ctx   context.Context
		JobID string
	}
	mock.lockGetJob.RLock()
	calls = mock.calls.GetJob
	mock.lockGetJob.RUnlock()
	return calls
}

// GetJobEvents calls GetJobEventsFunc.
func (mock *MongoDBMock) GetJobEvents(ctx context.Context, jobID string, limit int, offset int) ([]*domain.Event, int, error) {
	if mock.GetJobEventsFunc == nil {
		panic("MongoDBMock.GetJobEventsFunc: method is nil but MongoDB.GetJobEvents was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		JobID  string
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		JobID:  jobID,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockGetJobEvents.Lock()
	mock.calls.GetJobEvents = append(mock.calls.GetJobEvents, callInfo)
	mock.lockGetJobEvents.Unlock()
	return mock.GetJobEventsFunc(ctx, jobID, limit, offset)
}

// GetJobEventsCalls gets all the calls that were made to GetJobEvents.
// Check the length with:
//
//	len(mockedMongoDB.GetJobEventsCalls())
func (mock *MongoDBMock) GetJobEventsCalls() []struct {
	Ctx    context.Context
	JobID  string
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		JobID  string
		Limit  int
		Offset int
	}
	mock.lockGetJobEvents.RLock()
	calls = mock.calls.GetJobEvents
	mock.lockGetJobEvents.RUnlock()
	return calls
}

// GetJobTasks calls GetJobTasksFunc.
func (mock *MongoDBMock) GetJobTasks(ctx context.Context, jobID string, limit int, offset int) ([]*domain.Task, int, error) {
	if mock.GetJobTasksFunc == nil {
		panic("MongoDBMock.GetJobTasksFunc: method is nil but MongoDB.GetJobTasks was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		JobID  string
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		JobID:  jobID,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockGetJobTasks.Lock()
	mock.calls.GetJobTasks = append(mock.calls.GetJobTasks, callInfo)
	mock.lockGetJobTasks.Unlock()
	return mock.GetJobTasksFunc(ctx, jobID, limit, offset)
}

// GetJobTasksCalls gets all the calls that were made to GetJobTasks.
// Check the length with:
//
//	len(mockedMongoDB.GetJobTasksCalls())
func (mock *MongoDBMock) GetJobTasksCalls() []struct {
	Ctx    context.Context
	JobID  string
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		JobID  string
		Limit  int
		Offset int
	}
	mock.lockGetJobTasks.RLock()
	calls = mock.calls.GetJobTasks
	mock.lockGetJobTasks.RUnlock()
	return calls
}

// GetJobs calls GetJobsFunc.
func (mock *MongoDBMock) GetJobs(ctx context.Context, states []domain.JobState, limit int, offset int) ([]*domain.Job, int, error) {
	if mock.GetJobsFunc == nil {
		panic("MongoDBMock.GetJobsFunc: method is nil but MongoDB.GetJobs was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		States []domain.JobState
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		States: states,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockGetJobs.Lock()
	mock.calls.GetJobs = append(mock.calls.GetJobs, callInfo)
	mock.lockGetJobs.Unlock()
	return mock.GetJobsFunc(ctx, states, limit, offset)
}

// GetJobsCalls gets all the calls that were made to GetJobs.
// Check the length with:
//
//	len(mockedMongoDB.GetJobsCalls())
func (mock *MongoDBMock) GetJobsCalls() []struct {
	Ctx    context.Context
	States []domain.JobState
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		States []domain.JobState
		Limit  int
		Offset int
	}
	mock.lockGetJobs.RLock()
	calls = mock.calls.GetJobs
	mock.lockGetJobs.RUnlock()
	return calls
}

// GetJobsByConfigAndState calls GetJobsByConfigAndStateFunc.
func (mock *MongoDBMock) GetJobsByConfigAndState(ctx context.Context, jc *domain.JobConfig, states []domain.JobState, limit int, offset int) ([]*domain.Job, error) {
	if mock.GetJobsByConfigAndStateFunc == nil {
		panic("MongoDBMock.GetJobsByConfigAndStateFunc: method is nil but MongoDB.GetJobsByConfigAndState was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Jc     *domain.JobConfig
		States []domain.JobState
		Limit  int
		Offset int
	}{
		Ctx:    ctx,
		Jc:     jc,
		States: states,
		Limit:  limit,
		Offset: offset,
	}
	mock.lockGetJobsByConfigAndState.Lock()
	mock.calls.GetJobsByConfigAndState = append(mock.calls.GetJobsByConfigAndState, callInfo)
	mock.lockGetJobsByConfigAndState.Unlock()
	return mock.GetJobsByConfigAndStateFunc(ctx, jc, states, limit, offset)
}

// GetJobsByConfigAndStateCalls gets all the calls that were made to GetJobsByConfigAndState.
// Check the length with:
//
//	len(mockedMongoDB.GetJobsByConfigAndStateCalls())
func (mock *MongoDBMock) GetJobsByConfigAndStateCalls() []struct {
	Ctx    context.Context
	Jc     *domain.JobConfig
	States []domain.JobState
	Limit  int
	Offset int
} {
	var calls []struct {
		Ctx    context.Context
		Jc     *domain.JobConfig
		States []domain.JobState
		Limit  int
		Offset int
	}
	mock.lockGetJobsByConfigAndState.RLock()
	calls = mock.calls.GetJobsByConfigAndState
	mock.lockGetJobsByConfigAndState.RUnlock()
	return calls
}
