// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-migration-service/clients"
	"github.com/ONSdigital/dp-api-clients-go/v2/zebedee"
	"sync"
)

// Ensure, that ZebedeeClientMock does implement clients.ZebedeeClient.
// If this is not the case, regenerate this file with moq.
var _ clients.ZebedeeClient = &ZebedeeClientMock{}

// ZebedeeClientMock is a mock implementation of clients.ZebedeeClient.
//
//	func TestSomethingThatUsesZebedeeClient(t *testing.T) {
//
//		// make and configure a mocked clients.ZebedeeClient
//		mockedZebedeeClient := &ZebedeeClientMock{
//			GetDatasetLandingPageFunc: func(ctx context.Context, userAccessToken string, collectionID string, lang string, path string) (zebedee.DatasetLandingPage, error) {
//				panic("mock out the GetDatasetLandingPage method")
//			},
//			GetPageDataFunc: func(ctx context.Context, userAuthToken string, collectionID string, lang string, path string) (zebedee.PageData, error) {
//				panic("mock out the GetPageData method")
//			},
//		}
//
//		// use mockedZebedeeClient in code that requires clients.ZebedeeClient
//		// and then make assertions.
//
//	}
type ZebedeeClientMock struct {
	// GetDatasetLandingPageFunc mocks the GetDatasetLandingPage method.
	GetDatasetLandingPageFunc func(ctx context.Context, userAccessToken string, collectionID string, lang string, path string) (zebedee.DatasetLandingPage, error)

	// GetPageDataFunc mocks the GetPageData method.
	GetPageDataFunc func(ctx context.Context, userAuthToken string, collectionID string, lang string, path string) (zebedee.PageData, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetDatasetLandingPage holds details about calls to the GetDatasetLandingPage method.
		GetDatasetLandingPage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAccessToken is the userAccessToken argument value.
			UserAccessToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// Path is the path argument value.
			Path string
		}
		// GetPageData holds details about calls to the GetPageData method.
		GetPageData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAuthToken is the userAuthToken argument value.
			UserAuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// Path is the path argument value.
			Path string
		}
	}
	lockGetDatasetLandingPage sync.RWMutex
	lockGetPageData           sync.RWMutex
}

// GetDatasetLandingPage calls GetDatasetLandingPageFunc.
func (mock *ZebedeeClientMock) GetDatasetLandingPage(ctx context.Context, userAccessToken string, collectionID string, lang string, path string) (zebedee.DatasetLandingPage, error) {
	if mock.GetDatasetLandingPageFunc == nil {
		panic("ZebedeeClientMock.GetDatasetLandingPageFunc: method is nil but ZebedeeClient.GetDatasetLandingPage was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		UserAccessToken string
		CollectionID    string
		Lang            string
		Path            string
	}{
		Ctx:             ctx,
		UserAccessToken: userAccessToken,
		CollectionID:    collectionID,
		Lang:            lang,
		Path:            path,
	}
	mock.lockGetDatasetLandingPage.Lock()
	mock.calls.GetDatasetLandingPage = append(mock.calls.GetDatasetLandingPage, callInfo)
	mock.lockGetDatasetLandingPage.Unlock()
	return mock.GetDatasetLandingPageFunc(ctx, userAccessToken, collectionID, lang, path)
}

// GetDatasetLandingPageCalls gets all the calls that were made to GetDatasetLandingPage.
// Check the length with:
//
//	len(mockedZebedeeClient.GetDatasetLandingPageCalls())
func (mock *ZebedeeClientMock) GetDatasetLandingPageCalls() []struct {
	Ctx             context.Context
	UserAccessToken string
	CollectionID    string
	Lang            string
	Path            string
} {
	var calls []struct {
		Ctx             context.Context
		UserAccessToken string
		CollectionID    string
		Lang            string
		Path            string
	}
	mock.lockGetDatasetLandingPage.RLock()
	calls = mock.calls.GetDatasetLandingPage
	mock.lockGetDatasetLandingPage.RUnlock()
	return calls
}

// GetPageData calls GetPageDataFunc.
func (mock *ZebedeeClientMock) GetPageData(ctx context.Context, userAuthToken string, collectionID string, lang string, path string) (zebedee.PageData, error) {
	if mock.GetPageDataFunc == nil {
		panic("ZebedeeClientMock.GetPageDataFunc: method is nil but ZebedeeClient.GetPageData was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		UserAuthToken string
		CollectionID  string
		Lang          string
		Path          string
	}{
		Ctx:           ctx,
		UserAuthToken: userAuthToken,
		CollectionID:  collectionID,
		Lang:          lang,
		Path:          path,
	}
	mock.lockGetPageData.Lock()
	mock.calls.GetPageData = append(mock.calls.GetPageData, callInfo)
	mock.lockGetPageData.Unlock()
	return mock.GetPageDataFunc(ctx, userAuthToken, collectionID, lang, path)
}

// GetPageDataCalls gets all the calls that were made to GetPageData.
// Check the length with:
//
//	len(mockedZebedeeClient.GetPageDataCalls())
func (mock *ZebedeeClientMock) GetPageDataCalls() []struct {
	Ctx           context.Context
	UserAuthToken string
	CollectionID  string
	Lang          string
	Path          string
} {
	var calls []struct {
		Ctx           context.Context
		UserAuthToken string
		CollectionID  string
		Lang          string
		Path          string
	}
	mock.lockGetPageData.RLock()
	calls = mock.calls.GetPageData
	mock.lockGetPageData.RUnlock()
	return calls
}
