// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-migration-service/clients"
	"github.com/ONSdigital/dp-api-clients-go/v2/zebedee"
	"io"
	"sync"
)

// Ensure, that ZebedeeClientMock does implement clients.ZebedeeClient.
// If this is not the case, regenerate this file with moq.
var _ clients.ZebedeeClient = &ZebedeeClientMock{}

// ZebedeeClientMock is a mock implementation of clients.ZebedeeClient.
//
//	func TestSomethingThatUsesZebedeeClient(t *testing.T) {
//
//		// make and configure a mocked clients.ZebedeeClient
//		mockedZebedeeClient := &ZebedeeClientMock{
//			ApproveCollectionFunc: func(ctx context.Context, authToken string, collectionID string) error {
//				panic("mock out the ApproveCollection method")
//			},
//			ApproveCollectionContentFunc: func(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error {
//				panic("mock out the ApproveCollectionContent method")
//			},
//			CompleteCollectionContentFunc: func(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error {
//				panic("mock out the CompleteCollectionContent method")
//			},
//			CreateCollectionFunc: func(ctx context.Context, authToken string, collection zebedee.Collection) (zebedee.Collection, error) {
//				panic("mock out the CreateCollection method")
//			},
//			DeleteCollectionFunc: func(ctx context.Context, userAuthToken string, collectionID string) error {
//				panic("mock out the DeleteCollection method")
//			},
//			DeleteCollectionContentFunc: func(ctx context.Context, userAuthToken string, collectionID string, path string) error {
//				panic("mock out the DeleteCollectionContent method")
//			},
//			GetCollectionFunc: func(ctx context.Context, authToken string, collectionID string) (zebedee.Collection, error) {
//				panic("mock out the GetCollection method")
//			},
//			GetDatasetFunc: func(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.Dataset, error) {
//				panic("mock out the GetDataset method")
//			},
//			GetDatasetLandingPageFunc: func(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.DatasetLandingPage, error) {
//				panic("mock out the GetDatasetLandingPage method")
//			},
//			GetFileSizeFunc: func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.FileSize, error) {
//				panic("mock out the GetFileSize method")
//			},
//			GetPageDataFunc: func(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.PageData, error) {
//				panic("mock out the GetPageData method")
//			},
//			GetResourceStreamFunc: func(ctx context.Context, authToken string, collectionID string, lang string, path string) (io.ReadCloser, error) {
//				panic("mock out the GetResourceStream method")
//			},
//			SaveContentToCollectionFunc: func(ctx context.Context, authToken string, collectionID string, path string, content interface{}) error {
//				panic("mock out the SaveContentToCollection method")
//			},
//		}
//
//		// use mockedZebedeeClient in code that requires clients.ZebedeeClient
//		// and then make assertions.
//
//	}
type ZebedeeClientMock struct {
	// ApproveCollectionFunc mocks the ApproveCollection method.
	ApproveCollectionFunc func(ctx context.Context, authToken string, collectionID string) error

	// ApproveCollectionContentFunc mocks the ApproveCollectionContent method.
	ApproveCollectionContentFunc func(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error

	// CompleteCollectionContentFunc mocks the CompleteCollectionContent method.
	CompleteCollectionContentFunc func(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error

	// CreateCollectionFunc mocks the CreateCollection method.
	CreateCollectionFunc func(ctx context.Context, authToken string, collection zebedee.Collection) (zebedee.Collection, error)

	// DeleteCollectionFunc mocks the DeleteCollection method.
	DeleteCollectionFunc func(ctx context.Context, userAuthToken string, collectionID string) error

	// DeleteCollectionContentFunc mocks the DeleteCollectionContent method.
	DeleteCollectionContentFunc func(ctx context.Context, userAuthToken string, collectionID string, path string) error

	// GetCollectionFunc mocks the GetCollection method.
	GetCollectionFunc func(ctx context.Context, authToken string, collectionID string) (zebedee.Collection, error)

	// GetDatasetFunc mocks the GetDataset method.
	GetDatasetFunc func(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.Dataset, error)

	// GetDatasetLandingPageFunc mocks the GetDatasetLandingPage method.
	GetDatasetLandingPageFunc func(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.DatasetLandingPage, error)

	// GetFileSizeFunc mocks the GetFileSize method.
	GetFileSizeFunc func(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.FileSize, error)

	// GetPageDataFunc mocks the GetPageData method.
	GetPageDataFunc func(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.PageData, error)

	// GetResourceStreamFunc mocks the GetResourceStream method.
	GetResourceStreamFunc func(ctx context.Context, authToken string, collectionID string, lang string, path string) (io.ReadCloser, error)

	// SaveContentToCollectionFunc mocks the SaveContentToCollection method.
	SaveContentToCollectionFunc func(ctx context.Context, authToken string, collectionID string, path string, content interface{}) error

	// calls tracks calls to the methods.
	calls struct {
		// ApproveCollection holds details about calls to the ApproveCollection method.
		ApproveCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
		}
		// ApproveCollectionContent holds details about calls to the ApproveCollectionContent method.
		ApproveCollectionContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// PagePath is the pagePath argument value.
			PagePath string
		}
		// CompleteCollectionContent holds details about calls to the CompleteCollectionContent method.
		CompleteCollectionContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// PagePath is the pagePath argument value.
			PagePath string
		}
		// CreateCollection holds details about calls to the CreateCollection method.
		CreateCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// Collection is the collection argument value.
			Collection zebedee.Collection
		}
		// DeleteCollection holds details about calls to the DeleteCollection method.
		DeleteCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAuthToken is the userAuthToken argument value.
			UserAuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
		}
		// DeleteCollectionContent holds details about calls to the DeleteCollectionContent method.
		DeleteCollectionContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAuthToken is the userAuthToken argument value.
			UserAuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Path is the path argument value.
			Path string
		}
		// GetCollection holds details about calls to the GetCollection method.
		GetCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
		}
		// GetDataset holds details about calls to the GetDataset method.
		GetDataset []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// Path is the path argument value.
			Path string
		}
		// GetDatasetLandingPage holds details about calls to the GetDatasetLandingPage method.
		GetDatasetLandingPage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// Path is the path argument value.
			Path string
		}
		// GetFileSize holds details about calls to the GetFileSize method.
		GetFileSize []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// URI is the uri argument value.
			URI string
		}
		// GetPageData holds details about calls to the GetPageData method.
		GetPageData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// Path is the path argument value.
			Path string
		}
		// GetResourceStream holds details about calls to the GetResourceStream method.
		GetResourceStream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
			// Path is the path argument value.
			Path string
		}
		// SaveContentToCollection holds details about calls to the SaveContentToCollection method.
		SaveContentToCollection []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthToken is the authToken argument value.
			AuthToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Path is the path argument value.
			Path string
			// Content is the content argument value.
			Content interface{}
		}
	}
	lockApproveCollection         sync.RWMutex
	lockApproveCollectionContent  sync.RWMutex
	lockCompleteCollectionContent sync.RWMutex
	lockCreateCollection          sync.RWMutex
	lockDeleteCollection          sync.RWMutex
	lockDeleteCollectionContent   sync.RWMutex
	lockGetCollection             sync.RWMutex
	lockGetDataset                sync.RWMutex
	lockGetDatasetLandingPage     sync.RWMutex
	lockGetFileSize               sync.RWMutex
	lockGetPageData               sync.RWMutex
	lockGetResourceStream         sync.RWMutex
	lockSaveContentToCollection   sync.RWMutex
}

// ApproveCollection calls ApproveCollectionFunc.
func (mock *ZebedeeClientMock) ApproveCollection(ctx context.Context, authToken string, collectionID string) error {
	if mock.ApproveCollectionFunc == nil {
		panic("ZebedeeClientMock.ApproveCollectionFunc: method is nil but ZebedeeClient.ApproveCollection was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
	}
	mock.lockApproveCollection.Lock()
	mock.calls.ApproveCollection = append(mock.calls.ApproveCollection, callInfo)
	mock.lockApproveCollection.Unlock()
	return mock.ApproveCollectionFunc(ctx, authToken, collectionID)
}

// ApproveCollectionCalls gets all the calls that were made to ApproveCollection.
// Check the length with:
//
//	len(mockedZebedeeClient.ApproveCollectionCalls())
func (mock *ZebedeeClientMock) ApproveCollectionCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}
	mock.lockApproveCollection.RLock()
	calls = mock.calls.ApproveCollection
	mock.lockApproveCollection.RUnlock()
	return calls
}

// ApproveCollectionContent calls ApproveCollectionContentFunc.
func (mock *ZebedeeClientMock) ApproveCollectionContent(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error {
	if mock.ApproveCollectionContentFunc == nil {
		panic("ZebedeeClientMock.ApproveCollectionContentFunc: method is nil but ZebedeeClient.ApproveCollectionContent was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		PagePath     string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		PagePath:     pagePath,
	}
	mock.lockApproveCollectionContent.Lock()
	mock.calls.ApproveCollectionContent = append(mock.calls.ApproveCollectionContent, callInfo)
	mock.lockApproveCollectionContent.Unlock()
	return mock.ApproveCollectionContentFunc(ctx, authToken, collectionID, lang, pagePath)
}

// ApproveCollectionContentCalls gets all the calls that were made to ApproveCollectionContent.
// Check the length with:
//
//	len(mockedZebedeeClient.ApproveCollectionContentCalls())
func (mock *ZebedeeClientMock) ApproveCollectionContentCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	PagePath     string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		PagePath     string
	}
	mock.lockApproveCollectionContent.RLock()
	calls = mock.calls.ApproveCollectionContent
	mock.lockApproveCollectionContent.RUnlock()
	return calls
}

// CompleteCollectionContent calls CompleteCollectionContentFunc.
func (mock *ZebedeeClientMock) CompleteCollectionContent(ctx context.Context, authToken string, collectionID string, lang string, pagePath string) error {
	if mock.CompleteCollectionContentFunc == nil {
		panic("ZebedeeClientMock.CompleteCollectionContentFunc: method is nil but ZebedeeClient.CompleteCollectionContent was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		PagePath     string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		PagePath:     pagePath,
	}
	mock.lockCompleteCollectionContent.Lock()
	mock.calls.CompleteCollectionContent = append(mock.calls.CompleteCollectionContent, callInfo)
	mock.lockCompleteCollectionContent.Unlock()
	return mock.CompleteCollectionContentFunc(ctx, authToken, collectionID, lang, pagePath)
}

// CompleteCollectionContentCalls gets all the calls that were made to CompleteCollectionContent.
// Check the length with:
//
//	len(mockedZebedeeClient.CompleteCollectionContentCalls())
func (mock *ZebedeeClientMock) CompleteCollectionContentCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	PagePath     string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		PagePath     string
	}
	mock.lockCompleteCollectionContent.RLock()
	calls = mock.calls.CompleteCollectionContent
	mock.lockCompleteCollectionContent.RUnlock()
	return calls
}

// CreateCollection calls CreateCollectionFunc.
func (mock *ZebedeeClientMock) CreateCollection(ctx context.Context, authToken string, collection zebedee.Collection) (zebedee.Collection, error) {
	if mock.CreateCollectionFunc == nil {
		panic("ZebedeeClientMock.CreateCollectionFunc: method is nil but ZebedeeClient.CreateCollection was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		AuthToken  string
		Collection zebedee.Collection
	}{
		Ctx:        ctx,
		AuthToken:  authToken,
		Collection: collection,
	}
	mock.lockCreateCollection.Lock()
	mock.calls.CreateCollection = append(mock.calls.CreateCollection, callInfo)
	mock.lockCreateCollection.Unlock()
	return mock.CreateCollectionFunc(ctx, authToken, collection)
}

// CreateCollectionCalls gets all the calls that were made to CreateCollection.
// Check the length with:
//
//	len(mockedZebedeeClient.CreateCollectionCalls())
func (mock *ZebedeeClientMock) CreateCollectionCalls() []struct {
	Ctx        context.Context
	AuthToken  string
	Collection zebedee.Collection
} {
	var calls []struct {
		Ctx        context.Context
		AuthToken  string
		Collection zebedee.Collection
	}
	mock.lockCreateCollection.RLock()
	calls = mock.calls.CreateCollection
	mock.lockCreateCollection.RUnlock()
	return calls
}

// DeleteCollection calls DeleteCollectionFunc.
func (mock *ZebedeeClientMock) DeleteCollection(ctx context.Context, userAuthToken string, collectionID string) error {
	if mock.DeleteCollectionFunc == nil {
		panic("ZebedeeClientMock.DeleteCollectionFunc: method is nil but ZebedeeClient.DeleteCollection was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		UserAuthToken string
		CollectionID  string
	}{
		Ctx:           ctx,
		UserAuthToken: userAuthToken,
		CollectionID:  collectionID,
	}
	mock.lockDeleteCollection.Lock()
	mock.calls.DeleteCollection = append(mock.calls.DeleteCollection, callInfo)
	mock.lockDeleteCollection.Unlock()
	return mock.DeleteCollectionFunc(ctx, userAuthToken, collectionID)
}

// DeleteCollectionCalls gets all the calls that were made to DeleteCollection.
// Check the length with:
//
//	len(mockedZebedeeClient.DeleteCollectionCalls())
func (mock *ZebedeeClientMock) DeleteCollectionCalls() []struct {
	Ctx           context.Context
	UserAuthToken string
	CollectionID  string
} {
	var calls []struct {
		Ctx           context.Context
		UserAuthToken string
		CollectionID  string
	}
	mock.lockDeleteCollection.RLock()
	calls = mock.calls.DeleteCollection
	mock.lockDeleteCollection.RUnlock()
	return calls
}

// DeleteCollectionContent calls DeleteCollectionContentFunc.
func (mock *ZebedeeClientMock) DeleteCollectionContent(ctx context.Context, userAuthToken string, collectionID string, path string) error {
	if mock.DeleteCollectionContentFunc == nil {
		panic("ZebedeeClientMock.DeleteCollectionContentFunc: method is nil but ZebedeeClient.DeleteCollectionContent was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		UserAuthToken string
		CollectionID  string
		Path          string
	}{
		Ctx:           ctx,
		UserAuthToken: userAuthToken,
		CollectionID:  collectionID,
		Path:          path,
	}
	mock.lockDeleteCollectionContent.Lock()
	mock.calls.DeleteCollectionContent = append(mock.calls.DeleteCollectionContent, callInfo)
	mock.lockDeleteCollectionContent.Unlock()
	return mock.DeleteCollectionContentFunc(ctx, userAuthToken, collectionID, path)
}

// DeleteCollectionContentCalls gets all the calls that were made to DeleteCollectionContent.
// Check the length with:
//
//	len(mockedZebedeeClient.DeleteCollectionContentCalls())
func (mock *ZebedeeClientMock) DeleteCollectionContentCalls() []struct {
	Ctx           context.Context
	UserAuthToken string
	CollectionID  string
	Path          string
} {
	var calls []struct {
		Ctx           context.Context
		UserAuthToken string
		CollectionID  string
		Path          string
	}
	mock.lockDeleteCollectionContent.RLock()
	calls = mock.calls.DeleteCollectionContent
	mock.lockDeleteCollectionContent.RUnlock()
	return calls
}

// GetCollection calls GetCollectionFunc.
func (mock *ZebedeeClientMock) GetCollection(ctx context.Context, authToken string, collectionID string) (zebedee.Collection, error) {
	if mock.GetCollectionFunc == nil {
		panic("ZebedeeClientMock.GetCollectionFunc: method is nil but ZebedeeClient.GetCollection was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
	}
	mock.lockGetCollection.Lock()
	mock.calls.GetCollection = append(mock.calls.GetCollection, callInfo)
	mock.lockGetCollection.Unlock()
	return mock.GetCollectionFunc(ctx, authToken, collectionID)
}

// GetCollectionCalls gets all the calls that were made to GetCollection.
// Check the length with:
//
//	len(mockedZebedeeClient.GetCollectionCalls())
func (mock *ZebedeeClientMock) GetCollectionCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
	}
	mock.lockGetCollection.RLock()
	calls = mock.calls.GetCollection
	mock.lockGetCollection.RUnlock()
	return calls
}

// GetDataset calls GetDatasetFunc.
func (mock *ZebedeeClientMock) GetDataset(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.Dataset, error) {
	if mock.GetDatasetFunc == nil {
		panic("ZebedeeClientMock.GetDatasetFunc: method is nil but ZebedeeClient.GetDataset was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		Path:         path,
	}
	mock.lockGetDataset.Lock()
	mock.calls.GetDataset = append(mock.calls.GetDataset, callInfo)
	mock.lockGetDataset.Unlock()
	return mock.GetDatasetFunc(ctx, authToken, collectionID, lang, path)
}

// GetDatasetCalls gets all the calls that were made to GetDataset.
// Check the length with:
//
//	len(mockedZebedeeClient.GetDatasetCalls())
func (mock *ZebedeeClientMock) GetDatasetCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	Path         string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}
	mock.lockGetDataset.RLock()
	calls = mock.calls.GetDataset
	mock.lockGetDataset.RUnlock()
	return calls
}

// GetDatasetLandingPage calls GetDatasetLandingPageFunc.
func (mock *ZebedeeClientMock) GetDatasetLandingPage(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.DatasetLandingPage, error) {
	if mock.GetDatasetLandingPageFunc == nil {
		panic("ZebedeeClientMock.GetDatasetLandingPageFunc: method is nil but ZebedeeClient.GetDatasetLandingPage was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		Path:         path,
	}
	mock.lockGetDatasetLandingPage.Lock()
	mock.calls.GetDatasetLandingPage = append(mock.calls.GetDatasetLandingPage, callInfo)
	mock.lockGetDatasetLandingPage.Unlock()
	return mock.GetDatasetLandingPageFunc(ctx, authToken, collectionID, lang, path)
}

// GetDatasetLandingPageCalls gets all the calls that were made to GetDatasetLandingPage.
// Check the length with:
//
//	len(mockedZebedeeClient.GetDatasetLandingPageCalls())
func (mock *ZebedeeClientMock) GetDatasetLandingPageCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	Path         string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}
	mock.lockGetDatasetLandingPage.RLock()
	calls = mock.calls.GetDatasetLandingPage
	mock.lockGetDatasetLandingPage.RUnlock()
	return calls
}

// GetFileSize calls GetFileSizeFunc.
func (mock *ZebedeeClientMock) GetFileSize(ctx context.Context, authToken string, collectionID string, lang string, uri string) (zebedee.FileSize, error) {
	if mock.GetFileSizeFunc == nil {
		panic("ZebedeeClientMock.GetFileSizeFunc: method is nil but ZebedeeClient.GetFileSize was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		URI:          uri,
	}
	mock.lockGetFileSize.Lock()
	mock.calls.GetFileSize = append(mock.calls.GetFileSize, callInfo)
	mock.lockGetFileSize.Unlock()
	return mock.GetFileSizeFunc(ctx, authToken, collectionID, lang, uri)
}

// GetFileSizeCalls gets all the calls that were made to GetFileSize.
// Check the length with:
//
//	len(mockedZebedeeClient.GetFileSizeCalls())
func (mock *ZebedeeClientMock) GetFileSizeCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	URI          string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		URI          string
	}
	mock.lockGetFileSize.RLock()
	calls = mock.calls.GetFileSize
	mock.lockGetFileSize.RUnlock()
	return calls
}

// GetPageData calls GetPageDataFunc.
func (mock *ZebedeeClientMock) GetPageData(ctx context.Context, authToken string, collectionID string, lang string, path string) (zebedee.PageData, error) {
	if mock.GetPageDataFunc == nil {
		panic("ZebedeeClientMock.GetPageDataFunc: method is nil but ZebedeeClient.GetPageData was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		Path:         path,
	}
	mock.lockGetPageData.Lock()
	mock.calls.GetPageData = append(mock.calls.GetPageData, callInfo)
	mock.lockGetPageData.Unlock()
	return mock.GetPageDataFunc(ctx, authToken, collectionID, lang, path)
}

// GetPageDataCalls gets all the calls that were made to GetPageData.
// Check the length with:
//
//	len(mockedZebedeeClient.GetPageDataCalls())
func (mock *ZebedeeClientMock) GetPageDataCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	Path         string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}
	mock.lockGetPageData.RLock()
	calls = mock.calls.GetPageData
	mock.lockGetPageData.RUnlock()
	return calls
}

// GetResourceStream calls GetResourceStreamFunc.
func (mock *ZebedeeClientMock) GetResourceStream(ctx context.Context, authToken string, collectionID string, lang string, path string) (io.ReadCloser, error) {
	if mock.GetResourceStreamFunc == nil {
		panic("ZebedeeClientMock.GetResourceStreamFunc: method is nil but ZebedeeClient.GetResourceStream was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Lang:         lang,
		Path:         path,
	}
	mock.lockGetResourceStream.Lock()
	mock.calls.GetResourceStream = append(mock.calls.GetResourceStream, callInfo)
	mock.lockGetResourceStream.Unlock()
	return mock.GetResourceStreamFunc(ctx, authToken, collectionID, lang, path)
}

// GetResourceStreamCalls gets all the calls that were made to GetResourceStream.
// Check the length with:
//
//	len(mockedZebedeeClient.GetResourceStreamCalls())
func (mock *ZebedeeClientMock) GetResourceStreamCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Lang         string
	Path         string
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Lang         string
		Path         string
	}
	mock.lockGetResourceStream.RLock()
	calls = mock.calls.GetResourceStream
	mock.lockGetResourceStream.RUnlock()
	return calls
}

// SaveContentToCollection calls SaveContentToCollectionFunc.
func (mock *ZebedeeClientMock) SaveContentToCollection(ctx context.Context, authToken string, collectionID string, path string, content interface{}) error {
	if mock.SaveContentToCollectionFunc == nil {
		panic("ZebedeeClientMock.SaveContentToCollectionFunc: method is nil but ZebedeeClient.SaveContentToCollection was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Path         string
		Content      interface{}
	}{
		Ctx:          ctx,
		AuthToken:    authToken,
		CollectionID: collectionID,
		Path:         path,
		Content:      content,
	}
	mock.lockSaveContentToCollection.Lock()
	mock.calls.SaveContentToCollection = append(mock.calls.SaveContentToCollection, callInfo)
	mock.lockSaveContentToCollection.Unlock()
	return mock.SaveContentToCollectionFunc(ctx, authToken, collectionID, path, content)
}

// SaveContentToCollectionCalls gets all the calls that were made to SaveContentToCollection.
// Check the length with:
//
//	len(mockedZebedeeClient.SaveContentToCollectionCalls())
func (mock *ZebedeeClientMock) SaveContentToCollectionCalls() []struct {
	Ctx          context.Context
	AuthToken    string
	CollectionID string
	Path         string
	Content      interface{}
} {
	var calls []struct {
		Ctx          context.Context
		AuthToken    string
		CollectionID string
		Path         string
		Content      interface{}
	}
	mock.lockSaveContentToCollection.RLock()
	calls = mock.calls.SaveContentToCollection
	mock.lockSaveContentToCollection.RUnlock()
	return calls
}
