name: Dependabot Slack Notification

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Post to Slack
        uses: slackapi/slack-github-action@v3.0.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_CODE_REVIEW }}
          webhook-type: incoming-webhook
          payload: |
            text: "format('<{0}|{0}> - Dependabot opened a PR: {1}', github.event.pull_request.html_url, github.event.pull_request.title) }}"

