// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-migration-service/domain"
	"github.com/ONSdigital/dis-migration-service/executor"
	"sync"
)

// Ensure, that JobExecutorMock does implement executor.JobExecutor.
// If this is not the case, regenerate this file with moq.
var _ executor.JobExecutor = &JobExecutorMock{}

// JobExecutorMock is a mock implementation of executor.JobExecutor.
//
//	func TestSomethingThatUsesJobExecutor(t *testing.T) {
//
//		// make and configure a mocked executor.JobExecutor
//		mockedJobExecutor := &JobExecutorMock{
//			MigrateFunc: func(ctx context.Context, job *domain.Job) error {
//				panic("mock out the Migrate method")
//			},
//			PostPublishFunc: func(ctx context.Context, job *domain.Job) error {
//				panic("mock out the PostPublish method")
//			},
//			PublishFunc: func(ctx context.Context, job *domain.Job) error {
//				panic("mock out the Publish method")
//			},
//			RevertFunc: func(ctx context.Context, job *domain.Job) error {
//				panic("mock out the Revert method")
//			},
//		}
//
//		// use mockedJobExecutor in code that requires executor.JobExecutor
//		// and then make assertions.
//
//	}
type JobExecutorMock struct {
	// MigrateFunc mocks the Migrate method.
	MigrateFunc func(ctx context.Context, job *domain.Job) error

	// PostPublishFunc mocks the PostPublish method.
	PostPublishFunc func(ctx context.Context, job *domain.Job) error

	// PublishFunc mocks the Publish method.
	PublishFunc func(ctx context.Context, job *domain.Job) error

	// RevertFunc mocks the Revert method.
	RevertFunc func(ctx context.Context, job *domain.Job) error

	// calls tracks calls to the methods.
	calls struct {
		// Migrate holds details about calls to the Migrate method.
		Migrate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Job is the job argument value.
			Job *domain.Job
		}
		// PostPublish holds details about calls to the PostPublish method.
		PostPublish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Job is the job argument value.
			Job *domain.Job
		}
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Job is the job argument value.
			Job *domain.Job
		}
		// Revert holds details about calls to the Revert method.
		Revert []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Job is the job argument value.
			Job *domain.Job
		}
	}
	lockMigrate     sync.RWMutex
	lockPostPublish sync.RWMutex
	lockPublish     sync.RWMutex
	lockRevert      sync.RWMutex
}

// Migrate calls MigrateFunc.
func (mock *JobExecutorMock) Migrate(ctx context.Context, job *domain.Job) error {
	if mock.MigrateFunc == nil {
		panic("JobExecutorMock.MigrateFunc: method is nil but JobExecutor.Migrate was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Job *domain.Job
	}{
		Ctx: ctx,
		Job: job,
	}
	mock.lockMigrate.Lock()
	mock.calls.Migrate = append(mock.calls.Migrate, callInfo)
	mock.lockMigrate.Unlock()
	return mock.MigrateFunc(ctx, job)
}

// MigrateCalls gets all the calls that were made to Migrate.
// Check the length with:
//
//	len(mockedJobExecutor.MigrateCalls())
func (mock *JobExecutorMock) MigrateCalls() []struct {
	Ctx context.Context
	Job *domain.Job
} {
	var calls []struct {
		Ctx context.Context
		Job *domain.Job
	}
	mock.lockMigrate.RLock()
	calls = mock.calls.Migrate
	mock.lockMigrate.RUnlock()
	return calls
}

// PostPublish calls PostPublishFunc.
func (mock *JobExecutorMock) PostPublish(ctx context.Context, job *domain.Job) error {
	if mock.PostPublishFunc == nil {
		panic("JobExecutorMock.PostPublishFunc: method is nil but JobExecutor.PostPublish was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Job *domain.Job
	}{
		Ctx: ctx,
		Job: job,
	}
	mock.lockPostPublish.Lock()
	mock.calls.PostPublish = append(mock.calls.PostPublish, callInfo)
	mock.lockPostPublish.Unlock()
	return mock.PostPublishFunc(ctx, job)
}

// PostPublishCalls gets all the calls that were made to PostPublish.
// Check the length with:
//
//	len(mockedJobExecutor.PostPublishCalls())
func (mock *JobExecutorMock) PostPublishCalls() []struct {
	Ctx context.Context
	Job *domain.Job
} {
	var calls []struct {
		Ctx context.Context
		Job *domain.Job
	}
	mock.lockPostPublish.RLock()
	calls = mock.calls.PostPublish
	mock.lockPostPublish.RUnlock()
	return calls
}

// Publish calls PublishFunc.
func (mock *JobExecutorMock) Publish(ctx context.Context, job *domain.Job) error {
	if mock.PublishFunc == nil {
		panic("JobExecutorMock.PublishFunc: method is nil but JobExecutor.Publish was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Job *domain.Job
	}{
		Ctx: ctx,
		Job: job,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	return mock.PublishFunc(ctx, job)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedJobExecutor.PublishCalls())
func (mock *JobExecutorMock) PublishCalls() []struct {
	Ctx context.Context
	Job *domain.Job
} {
	var calls []struct {
		Ctx context.Context
		Job *domain.Job
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}

// Revert calls RevertFunc.
func (mock *JobExecutorMock) Revert(ctx context.Context, job *domain.Job) error {
	if mock.RevertFunc == nil {
		panic("JobExecutorMock.RevertFunc: method is nil but JobExecutor.Revert was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Job *domain.Job
	}{
		Ctx: ctx,
		Job: job,
	}
	mock.lockRevert.Lock()
	mock.calls.Revert = append(mock.calls.Revert, callInfo)
	mock.lockRevert.Unlock()
	return mock.RevertFunc(ctx, job)
}

// RevertCalls gets all the calls that were made to Revert.
// Check the length with:
//
//	len(mockedJobExecutor.RevertCalls())
func (mock *JobExecutorMock) RevertCalls() []struct {
	Ctx context.Context
	Job *domain.Job
} {
	var calls []struct {
		Ctx context.Context
		Job *domain.Job
	}
	mock.lockRevert.RLock()
	calls = mock.calls.Revert
	mock.lockRevert.RUnlock()
	return calls
}
