// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ONSdigital/dis-migration-service/migrator"
	"sync"
)

// Ensure, that MigratorMock does implement migrator.Migrator.
// If this is not the case, regenerate this file with moq.
var _ migrator.Migrator = &MigratorMock{}

// MigratorMock is a mock implementation of migrator.Migrator.
//
// 	func TestSomethingThatUsesMigrator(t *testing.T) {
//
// 		// make and configure a mocked migrator.Migrator
// 		mockedMigrator := &MigratorMock{
// 			ShutdownFunc: func(ctx context.Context) error {
// 				panic("mock out the Shutdown method")
// 			},
// 			StartFunc: func(ctx context.Context)  {
// 				panic("mock out the Start method")
// 			},
// 		}
//
// 		// use mockedMigrator in code that requires migrator.Migrator
// 		// and then make assertions.
//
// 	}
type MigratorMock struct {
	// ShutdownFunc mocks the Shutdown method.
	ShutdownFunc func(ctx context.Context) error

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context)

	// calls tracks calls to the methods.
	calls struct {
		// Shutdown holds details about calls to the Shutdown method.
		Shutdown []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockShutdown sync.RWMutex
	lockStart    sync.RWMutex
}

// Shutdown calls ShutdownFunc.
func (mock *MigratorMock) Shutdown(ctx context.Context) error {
	if mock.ShutdownFunc == nil {
		panic("MigratorMock.ShutdownFunc: method is nil but Migrator.Shutdown was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockShutdown.Lock()
	mock.calls.Shutdown = append(mock.calls.Shutdown, callInfo)
	mock.lockShutdown.Unlock()
	return mock.ShutdownFunc(ctx)
}

// ShutdownCalls gets all the calls that were made to Shutdown.
// Check the length with:
//     len(mockedMigrator.ShutdownCalls())
func (mock *MigratorMock) ShutdownCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockShutdown.RLock()
	calls = mock.calls.Shutdown
	mock.lockShutdown.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *MigratorMock) Start(ctx context.Context) {
	if mock.StartFunc == nil {
		panic("MigratorMock.StartFunc: method is nil but Migrator.Start was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	mock.StartFunc(ctx)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//     len(mockedMigrator.StartCalls())
func (mock *MigratorMock) StartCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}
